ERROR_IDENTIFIERS = {
    1000: {'message': 'Invalid user input', 'description': None},
    1001: {'message': 'Invalid card status', 'description': None},
    1002: {'message': 'Currency mismatch', 'description': None},
    1003: {'message': 'Invalid iban', 'description': None},
    1004: {'message': 'Invalid bic', 'description': None},
    1005: {'message': 'Invalid beneficiary name', 'description': None},
    1006: {'message': 'Invalid payment purpose', 'description': None},
    1007: {'message': 'Invalid gender', 'description': None},
    1010: {'message': 'Invalid person name', 'description': None},
    1020: {'message': 'Invalid address', 'description': None},
    1030: {'message': 'Invalid date of birth', 'description': None},
    1040: {'message': 'Invalid email', 'description': None},
    1050: {'message': 'Invalid mobile phone number', 'description': None},
    2000: {'message': 'Load failed', 'description': 'No specific fail reason available'},
    2001: {
        'message': 'Daily load limit exceeded',
        'description': 'Additional parameters: ‘out.count’: Number of daily loads and ‘out.maxcount’: Number of allowed daily loads',
    },
    2002: {
        'message': 'Monthly load limit exceeded',
        'description': 'Additional parameters: out.count Number of monthly loads out.maxcount Number of allowed monthly loads',
    },
    2003: {
        'message': 'Guaranteed payments only',
        'description': 'The selected payment method offers no payment guarantee and is not available for this consumer',
    },
    2100: {
        'message': 'Load not allowed',
        'description': 'The card does not support (further) loading in its current state',
    },
    2101: {
        'message': 'Load amount too small',
        'description': 'Additional parameters: out.minimumamount Amount in out.currency ISO currency code (EUR, GPB etc.)',
    },
    2102: {
        'message': 'Load amount too large',
        'description': 'Additional parameters: out.maximumamount Amount in out.currency ISO currency code (EUR, USD, etc.)',
    },
    2200: {'message': 'Load held', 'description': 'The load has been held to prevent misused'},
    3000: {'message': 'Unload failed', 'description': 'No specific fail reason available'},
    3100: {'message': 'Unload not allowed', 'description': 'The card does not support unloading in its current state'},
    3101: {
        'message': 'Unload amount too small',
        'description': 'Additional parameters: out.minimumamount Amount in out.currency ISO currency code (EUR, GPB etc.)',
    },
    3102: {
        'message': 'Unload amount too large',
        'description': 'Additional parameters: out.maximumamount Amount in out.currency ISO currency code (EUR, GPB etc.)',
    },
    4000: {'message': 'Payment failed', 'description': 'The payment failed without a specific fail reason'},
    4100: {'message': 'Payment input rejected', 'description': 'The card’s customer data is not failed for payments'},
    4200: {'message': 'Payment aborted', 'description': 'The payment was aborted by the user'},
    4300: {'message': 'Payment timeout', 'description': 'Waited in vain for a status update'},
    4400: {'message': 'Payment error', 'description': 'A technical error occurred'},
    4500: {'message': 'Payment remote error', 'description': 'A technical error occurred in a remote service'},
    4600: {'message': 'Payment declined', 'description': 'The payment was declined'},
    4700: {'message': 'Payment remote declined', 'description': 'The payment was declined by a remote service'},
    5000: {'message': 'Order failed', 'description': 'The order was rejected.'},
    5100: {'message': 'Pep match abort', 'description': 'The order was rejected because of a match on the pep list.'},
    5200: {
        'message': 'Sanctions match abort',
        'description': 'The order was rejected because of a match on the sanctions list.',
    },
}
