#!/bin/sh

set -o errexit
set -o nounset

export DJANGO_SETTINGS_MODULE=project.settings.production
celery flower -A project \
--basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}" \
--broker=${REDIS_URL} \
--broker_api=${REDIS_URL} \
--persistent=True \
--db=flower/flower.db
