#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

export DJANGO_SETTINGS_MODULE=project.settings.production

python manage.py migrate --noinput
python manage.py collectstatic --noinput

gunicorn project.wsgi --bind 0.0.0.0:5000 --timeout 300 --chdir=/app
