# Generated by Django 2.1.7 on 2019-03-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundrequest',
            old_name='funded_at',
            new_name='updated_at',
        ),
    ]
