# Generated by Django 2.1.7 on 2019-03-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190305_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundrequest',
            old_name='amount',
            new_name='requested_amount',
        ),
    ]
