# Generated by Django 2.1.7 on 2019-03-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190305_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='actual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Actual amount'),
        ),
    ]
