# Generated by Django 2.1.7 on 2019-03-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fundrequest_actual_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Comment'),
        ),
    ]
