# Generated by Django 2.1.7 on 2019-03-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_accountimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted user'),
        ),
    ]
