# Generated by Django 2.1.7 on 2019-03-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fin_comment',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Financial Comment'),
        ),
    ]
