# Generated by Django 2.1.7 on 2019-03-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_account_fin_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='review_status',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('banned', 'Banned'), ('logout', 'Logged out'), ('verify', 'On verification')], default='active', max_length=16, verbose_name='Account status'),
        ),
    ]
