# Generated by Django 2.1.7 on 2019-03-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190311_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='fin_comment',
            new_name='financial_comment',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_status',
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Active'), (20, 'Banned'), (10, 'Logged out'), (30, 'On verification')], default=0, verbose_name='Account status'),
        ),
    ]
