# Generated by Django 2.1.7 on 2019-03-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190311_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Active'), (20, 'Banned'), (10, 'Logged out'), (30, 'On verification'), (40, 'Inactive')], default=0, verbose_name='Account status'),
        ),
    ]
