# Generated by Django 2.1.7 on 2019-03-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alerts',
            field=models.BooleanField(default=True, verbose_name='Send alerts'),
        ),
    ]
