# Generated by Django 2.1.7 on 2019-03-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('funds', 'Funds'), ('account', 'Account')], default='funds', max_length=16, verbose_name='Notification type'),
        ),
    ]
