# Generated by Django 2.1.7 on 2019-03-13 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190311_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senders_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('funds_create', 'Funds request create'), ('funds_done', 'Funds request processed'), ('account', 'Account')], default='funds', max_length=16, verbose_name='Notification type'),
        ),
    ]
