# Generated by Django 2.1.7 on 2019-03-14 10:14

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190313_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('funds_create', 'Funds request create'), ('funds_approved', 'Funds request approved'), ('funds_declined', 'Funds request declined'), ('account', 'Account')], default='funds', max_length=16, verbose_name='Notification type'),
        ),
    ]
