# Generated by Django 2.1.7 on 2019-03-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190314_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('funds_create', 'Funds request create'), ('funds_approved', 'Funds request approved'), ('funds_declined', 'Funds request declined'), ('account_changed', 'Account changed')], default='funds', max_length=16, verbose_name='Notification type'),
        ),
    ]
