# Generated by Django 2.1.7 on 2019-03-27 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190325_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Funded datetime'),
            preserve_default=False,
        ),
    ]
