# Generated by Django 2.2 on 2019-04-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Active'), (20, 'Banned'), (10, 'Logged out'), (30, 'On verification'), (40, 'Inactive'), (50, 'Surfing'), (60, 'Warming'), (70, 'Ready to setup')], default=0, verbose_name='Account status'),
        ),
    ]
