# Generated by Django 2.2 on 2019-08-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='page_id',
            field=models.BigIntegerField(verbose_name='Page ID'),
        ),
        migrations.AlterField(
            model_name='useremail',
            name='user_id',
            field=models.BigIntegerField(verbose_name='User ID'),
        ),
    ]
