# Generated by Django 2.2 on 2019-08-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190821_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremail',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone'),
        ),
    ]
