# Generated by Django 2.2 on 2019-09-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190925_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start using'),
        ),
        migrations.AddField(
            model_name='account',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Banned at'),
        ),
        migrations.AddField(
            model_name='account',
            name='surfing_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start surfing'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User name'),
        ),
    ]
