# Generated by Django 2.2 on 2019-09-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190925_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='domain',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='account',
            name='reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Domain change'), (20, 'Safe change')], null=True, verbose_name='Status change reason'),
        ),
        migrations.AddField(
            model_name='account',
            name='server',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='account',
            name='track_link',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Comment'),
        ),
    ]
