# Generated by Django 2.2 on 2019-09-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190925_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Admin'), (10, 'Mediabuyer'), (20, 'Financier'), (30, 'Farmer'), (40, 'Supplier'), (50, 'Setuper')], default=10, verbose_name='User role'),
        ),
    ]
