# Generated by Django 2.2 on 2019-09-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20190925_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='worming_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start worming'),
        ),
    ]
