# Generated by Django 2.2 on 2019-09-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_account_worming_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='worming_at',
        ),
        migrations.AddField(
            model_name='account',
            name='warming_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start warming'),
        ),
    ]
