# Generated by Django 2.2 on 2019-09-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20190926_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ban_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ban reason'),
        ),
    ]
