# Generated by Django 2.2 on 2019-09-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_account_ban_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Setup account'), (10, 'Domain change'), (20, 'Safe change')], null=True, verbose_name='Status change reason'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(100, 'New'), (0, 'Active'), (20, 'Banned'), (10, 'Logged out'), (30, 'On verification'), (40, 'Inactive'), (50, 'Surfing'), (60, 'Warming'), (0, 'Setup'), (70, 'Ready to setup')], default=100, verbose_name='Account status'),
        ),
    ]
