# Generated by Django 2.2 on 2019-09-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20190926_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='reason',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Setup account'), (10, 'Domain change'), (20, 'Safe change')], default=0, verbose_name='Status change reason'),
        ),
    ]
