# Generated by Django 2.2 on 2019-09-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20190926_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='domain',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='account',
            name='server',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Server name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='track_link',
            field=models.URLField(blank=True, max_length=4096, null=True, verbose_name='Track link'),
        ),
    ]
