# Generated by Django 2.2 on 2019-09-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20190926_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='label',
        ),
    ]
