# Generated by Django 2.2 on 2019-09-27 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_account_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Waiting'), (10, 'Processing'), (20, 'Declined'), (50, 'Done')], default=0, verbose_name='Request status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Account assign at')),
                ('decline_reason', models.CharField(blank=True, max_length=256, null=True, verbose_name='Decline reason')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is removed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
