# Generated by Django 2.2 on 2019-09-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_accountrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='approved_quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Approved accs'),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='requested_quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Requested accs'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Waiting'), (20, 'Declined'), (50, 'Done')], default=0, verbose_name='Request status'),
        ),
    ]
