# Generated by Django 2.2 on 2019-09-27 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20190927_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrequest',
            name='deleted',
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='processed_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_account_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
