# Generated by Django 2.2 on 2019-09-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20190927_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequest',
            name='approved_quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Approved accs'),
        ),
    ]
