# Generated by Django 2.2 on 2019-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20190930_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('funds_create', 'Funds request create'), ('accounts_request_create', 'Accs request create'), ('accounts_request_approved', 'Accs request approved'), ('accounts_request_declined', 'Accs request approved'), ('funds_declined', 'Funds request declined'), ('funds_declined', 'Funds request declined'), ('account_changed', 'Account changed')], default='funds', max_length=64, verbose_name='Notification type'),
        ),
    ]
