# Generated by Django 2.2 on 2019-10-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20191001_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status_comment',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Status Comment'),
        ),
    ]
