# Generated by Django 2.2 on 2019-10-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_usersetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSetting',
            new_name='FieldsSetting',
        ),
    ]
