# Generated by Django 2.2 on 2019-10-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20191009_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldssetting',
            old_name='data',
            new_name='fields',
        ),
    ]
