# Generated by Django 2.2 on 2019-10-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20191009_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldssetting',
            name='fields',
        ),
    ]
