# Generated by Django 2.2 on 2019-10-09 08:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_fieldssetting_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldssetting',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=[], size=None),
            preserve_default=False,
        ),
    ]
