# Generated by Django 2.2 on 2019-10-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_fieldssetting_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldssetting',
            name='action',
            field=models.CharField(choices=[('list', 'list'), ('retrieve', 'retrieve'), ('edit', 'edit')], default='list', max_length=32),
        ),
    ]
