# Generated by Django 2.2 on 2019-10-09 09:29
from django.db import migrations


def fill_supplier(apps, *args, **kwargs):
    Account = apps.get_model('core', 'Account')
    User = apps.get_model('core', 'User')
    supplier = User.objects.filter(role=40).first()
    if supplier:
        Account.objects.all().update(created_by=supplier)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0056_fieldssetting_action'),
    ]

    operations = [
        migrations.RunPython(fill_supplier),
    ]
