# Generated by Django 2.2.6 on 2019-10-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_account_prev_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reason',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Setup account'), (10, 'Domain change'), (20, 'Safe change')], default=0, verbose_name='Status change reason'),
        ),
    ]
