# Generated by Django 2.2.6 on 2019-10-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_account_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
