# Generated by Django 2.2.6 on 2019-10-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_account_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
