# Generated by Django 2.2.6 on 2019-10-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20191023_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
