# Generated by Django 2.2.7 on 2019-11-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_userdaystat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdaystat',
            unique_together={('user', 'date')},
        ),
    ]
