# Generated by Django 2.2.7 on 2019-11-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20191113_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdaystat',
            name='active_accs',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Active accs on current date'),
        ),
        migrations.AddField(
            model_name='userdaystat',
            name='banned_accs',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Banned accs'),
        ),
        migrations.AddField(
            model_name='userdaystat',
            name='leads',
            field=models.PositiveIntegerField(default=0, verbose_name='Leads'),
        ),
        migrations.AddField(
            model_name='userdaystat',
            name='spends',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Spends'),
        ),
    ]
