# Generated by Django 2.2.7 on 2019-11-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20191115_0831'),
        ('core', '0069_auto_20191114_1045'),
    ]

    operations = [
    ]
