# Generated by Django 2.2.7 on 2019-11-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_merge_20191115_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tracker_login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tracking_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdaystat',
            name='compensation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit Corrections'),
        ),
        migrations.AlterField(
            model_name='userdaystat',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit'),
        ),
    ]
