# Generated by Django 2.2.7 on 2019-11-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20191115_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tracking_password',
            new_name='tracker_password',
        ),
    ]
