# Generated by Django 2.2.7 on 2019-11-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20191115_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_alerts',
            field=models.BooleanField(default=True, verbose_name='Send alerts to telegram'),
        ),
    ]
