# Generated by Django 2.2.7 on 2019-11-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_user_telegram_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exclude_from_top',
            field=models.BooleanField(default=False, verbose_name='Exclude user from top'),
        ),
    ]
