# Generated by Django 2.2.7 on 2019-11-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_user_exclude_from_top'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdaystat',
            old_name='compensation',
            new_name='profit_correction',
        ),
    ]
