# Generated by Django 2.2.7 on 2019-11-25 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20191121_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Command name')),
                ('description', models.CharField(max_length=255, verbose_name='Command description')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Command'),
        ),
    ]
