# Generated by Django 2.2.7 on 2019-11-28 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20191125_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdaystat',
            name='clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Clicks'),
        ),
        migrations.AddField(
            model_name='userdaystat',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='userdaystat',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue'),
        ),
        migrations.AddField(
            model_name='userdaystat',
            name='visits',
            field=models.PositiveIntegerField(default=0, verbose_name='Visits'),
        ),
        migrations.CreateModel(
            name='CampaignDayStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('campaign_id', models.PositiveIntegerField()),
                ('campaign_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=2)),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visits')),
                ('leads', models.PositiveIntegerField(default=0, verbose_name='Leads')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'campaign_id')},
            },
        ),
    ]
