# Generated by Django 2.2.7 on 2019-11-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_auto_20191128_1256'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdaystat',
            unique_together={('command', 'user', 'date')},
        ),
    ]
