# Generated by Django 3.0 on 2019-12-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20191128_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='campaign_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tracker campaign ID'),
        ),
        migrations.AddField(
            model_name='account',
            name='fb_access_token',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='BM access token'),
        ),
    ]
