# Generated by Django 3.0 on 2019-12-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_auto_20191203_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fb_spends',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Account FB spands'),
        ),
        migrations.AddField(
            model_name='account',
            name='tracker_spends',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Account tracker spends'),
        ),
    ]
