# Generated by Django 2.2.8 on 2019-12-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20191203_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adaccount_name', models.CharField(max_length=256, verbose_name='Fb adaccount name')),
                ('adaccount_id', models.BigIntegerField(verbose_name='Fb adaccount id')),
                ('access_token', models.CharField(max_length=256, verbose_name='Access token')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaccounts', to='core.Account')),
            ],
        ),
    ]
