# Generated by Django 2.2.8 on 2019-12-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_adaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaccount',
            name='access_token',
        ),
        migrations.AddField(
            model_name='adaccount',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ad account is active'),
        ),
    ]
