# Generated by Django 2.2.8 on 2019-12-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20191205_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='fb_access_token',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='FB access token'),
        ),
    ]
