# Generated by Django 2.2.8 on 2019-12-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_auto_20191205_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
