# Generated by Django 2.2.8 on 2019-12-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_adaccount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='proxy_host',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='proxy_login',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='proxy_password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='proxy_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
