# Generated by Django 2.2.8 on 2019-12-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20191205_1220'),
        ('core', '0082_auto_20191205_1356'),
    ]

    operations = [
    ]
