# Generated by Django 2.2.8 on 2019-12-06 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_merge_20191205_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='logout_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Logout at'),
        ),
        migrations.AddField(
            model_name='adaccount',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adaccounts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
