# Generated by Django 2.2.8 on 2019-12-06 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20191206_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adaccount',
            old_name='adaccount_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='adaccount',
            name='is_active',
        ),
        migrations.AddField(
            model_name='adaccount',
            name='status',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ad account status'),
        ),
        migrations.AlterField(
            model_name='adaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
