# Generated by Django 2.2.8 on 2019-12-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_auto_20191206_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
