# Generated by Django 2.2.8 on 2019-12-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_adaccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fb_spends',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Account FB spends'),
        ),
        migrations.AlterField(
            model_name='adaccount',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount spends'),
        ),
        migrations.AlterField(
            model_name='adaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance'),
        ),
    ]
