# Generated by Django 2.2.8 on 2019-12-06 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_auto_20191206_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdAccountDayStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Spend')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
                ('adaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AdAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'account', 'adaccount', 'date')},
            },
        ),
    ]
