# Generated by Django 2.2.8 on 2019-12-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_adaccountdaystats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdAccountDayStats',
            new_name='AdAccountDayStat',
        ),
    ]
