# Generated by Django 2.2.8 on 2019-12-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20191206_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fb_spends_today',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Account FB spends today'),
        ),
        migrations.AddField(
            model_name='account',
            name='fb_spends_yesterday',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Account FB spends yesterday'),
        ),
    ]
