# Generated by Django 2.2.8 on 2019-12-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20191209_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaccount',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ACTIVE'), (2, 'DISABLED'), (3, 'UNSETTLED'), (7, 'PENDING RISK REVIEW'), (8, 'PENDING SETTLEMENT'), (9, 'IN GRACE PERIOD'), (100, 'PENDING CLOSURE'), (101, 'CLOSED'), (201, 'ANY ACTIVE'), (202, 'ANY CLOSED')], default=1, verbose_name='Ad account status'),
        ),
    ]
