# Generated by Django 2.2.8 on 2019-12-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_auto_20191210_0939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adaccountdaystat',
            unique_together={('account', 'adaccount', 'date')},
        ),
    ]
