# Generated by Django 2.2.8 on 2019-12-11 12:33

from django.db import migrations

def fill_proxy(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Account = apps.get_model("core", "Account")
    db_alias = schema_editor.connection.alias
    Account.objects.using(db_alias).all().update(
        proxy_host='sweetecom.keenetic.pro',
        proxy_login='proxy',
        proxy_password='bpQ6K3zGnuh66TPU'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20191210_1047'),
    ]

    operations = [
        migrations.RunPython(fill_proxy),
    ]