# Generated by Django 2.2.8 on 2019-12-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_auto_20191211_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_spends',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Account full spends'),
        ),
    ]
