# Generated by Django 2.2.8 on 2019-12-12 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_account_total_spends'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='disable_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ACTIVE'), (2, 'DISABLED'), (3, 'UNSETTLED'), (7, 'PENDING RISK REVIEW'), (8, 'PENDING SETTLEMENT'), (9, 'IN GRACE PERIOD'), (100, 'PENDING CLOSURE'), (101, 'CLOSED'), (201, 'ANY ACTIVE'), (202, 'ANY CLOSED')], default=None, null=True, verbose_name='Ad account disable reason'),
        ),
        migrations.CreateModel(
            name='FBPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.BigIntegerField(verbose_name='FB page id')),
                ('name', models.CharField(max_length=512, verbose_name='Page name')),
                ('page_token', models.CharField(max_length=255, verbose_name='Page access token')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
            options={
                'unique_together': {('account', 'page_id')},
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.BigIntegerField(verbose_name='FB page id')),
                ('name', models.CharField(max_length=512, verbose_name='Page name')),
                ('status', models.PositiveSmallIntegerField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DELETED', 'Deleted'), ('ARCHIVED', 'Archived')], default='ACTIVE', verbose_name='Ad account status')),
                ('ad_id', models.BigIntegerField(verbose_name='FB ad id')),
                ('creative_id', models.BigIntegerField(verbose_name='FB creative id')),
                ('story_id', models.CharField(max_length=64, verbose_name='FB story id')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
            options={
                'unique_together': {('account', 'page_id', 'ad_id')},
            },
        ),
    ]
