# Generated by Django 2.2.8 on 2019-12-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_auto_20191212_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaccount',
            name='disable_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ACTIVE'), (2, 'DISABLED'), (3, 'UNSETTLED'), (7, 'PENDING RISK REVIEW'), (8, 'PENDING SETTLEMENT'), (9, 'IN GRACE PERIOD'), (100, 'PENDING CLOSURE'), (101, 'CLOSED'), (201, 'ANY ACTIVE'), (202, 'ANY CLOSED')], default=0, null=True, verbose_name='Ad account disable reason'),
        ),
    ]
