# Generated by Django 2.2.8 on 2019-12-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_auto_20191212_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbpage',
            old_name='page_token',
            new_name='access_token',
        ),
    ]
