# Generated by Django 2.2.8 on 2019-12-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_auto_20191212_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='status',
        ),
    ]
