# Generated by Django 2.2.8 on 2019-12-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_ad_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ad',
            unique_together={('account', 'ad_id')},
        ),
        migrations.RemoveField(
            model_name='ad',
            name='page_id',
        ),
    ]
