# Generated by Django 2.2.8 on 2019-12-12 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_auto_20191212_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.FBPage'),
            preserve_default=False,
        ),
    ]
