# Generated by Django 2.2.8 on 2019-12-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_ad_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='adaccount',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, to='core.AdAccount'),
            preserve_default=False,
        ),
    ]
