# Generated by Django 2.2.8 on 2019-12-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_auto_20191212_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='effective_status',
            field=models.CharField(default='ACTIVE', max_length=12, verbose_name='Ad effective status'),
        ),
    ]
