# Generated by Django 2.2.8 on 2019-12-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_ad_effective_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='effective_status',
            field=models.CharField(default='ACTIVE', max_length=24, verbose_name='Ad effective status'),
        ),
    ]
