# Generated by Django 2.2.8 on 2019-12-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_auto_20191212_1226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ad',
            unique_together={('account', 'adaccount', 'ad_id', 'creative_id')},
        ),
    ]
