# Generated by Django 2.2.8 on 2019-12-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_auto_20191212_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='total_comments',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DELETED', 'Deleted'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12, verbose_name='Ad status'),
        ),
    ]
