# Generated by Django 2.2.8 on 2019-12-12 15:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_auto_20191212_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='adpixels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
    ]
