# Generated by Django 2.2.8 on 2019-12-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_adaccount_adpixels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adaccount',
            old_name='adpixels',
            new_name='adspixels',
        ),
    ]
