# Generated by Django 2.2.8 on 2019-12-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_auto_20191212_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FBPage'),
        ),
        migrations.AlterField(
            model_name='adaccount',
            name='disable_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'NONE'), (1, 'ADS INTEGRITY POLICY'), (2, 'ADS IP REVIEW'), (3, 'RISK PAYMENT'), (4, 'GRAY ACCOUNT SHUT DOWN'), (5, 'ADS AFC REVIEW'), (6, 'BUSINESS INTEGRITY RAR'), (7, 'PERMANENT CLOSE'), (8, 'UNUSED RESELLER ACCOUNT'), (9, 'UNUSED ACCOUNT')], default=0, null=True, verbose_name='Ad account disable reason'),
        ),
    ]
