# Generated by Django 2.2.8 on 2019-12-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_auto_20191212_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='effective_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PAUSED', 'PAUSED'), ('DELETED', 'DELETED'), ('PENDING_REVIEW', 'PENDING_REVIEW'), ('DISAPPROVED', 'DISAPPROVED'), ('PREAPPROVED', 'PREAPPROVED'), ('PENDING_BILLING_INFO', 'PENDING_BILLING_INFO'), ('CAMPAIGN_PAUSED', 'CAMPAIGN_PAUSED'), ('ARCHIVED', 'ARCHIVED'), ('ADSET_PAUSED', 'ADSET_PAUSED'), ('IN_PROCESS', 'IN_PROCESS'), ('WITH_ISSUES', 'WITH_ISSUES')], default='ACTIVE', max_length=24, verbose_name='Ad effective status'),
        ),
    ]
