# Generated by Django 2.2.8 on 2019-12-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_auto_20191213_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_review_feedback',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Review Feedback'),
        ),
    ]
