# Generated by Django 2.2.8 on 2019-12-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_ad_ad_review_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
