# Generated by Django 2.2.8 on 2019-12-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_ad_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_review_feedback',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Review Feedback'),
        ),
    ]
