# Generated by Django 2.2.8 on 2019-12-13 14:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_auto_20191213_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_review_feedback_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Review Feedback code'),
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_review_feedback_text',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Review Feedback text'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_review_feedback',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, max_length=4096, null=True, verbose_name='Review Feedback'),
        ),
    ]
