# Generated by Django 2.2.8 on 2019-12-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_auto_20191213_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fb_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Account FB Balance'),
        ),
    ]
