# Generated by Django 2.2.8 on 2019-12-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_account_fb_balance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adaccount',
            unique_together={('account', 'adaccount_id')},
        ),
    ]
