# Generated by Django 2.2.8 on 2019-12-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_account_fb_balance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Command',
            new_name='Team',
        ),
    ]
