# Generated by Django 2.2.8 on 2019-12-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_auto_20191218_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='command',
            new_name='team',
        ),
    ]
