# Generated by Django 3.0.1 on 2019-12-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_auto_20191218_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alerts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='exclude_from_top',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_alerts',
        ),
        migrations.AddField(
            model_name='user',
            name='proxy_host',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='proxy_login',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='proxy_password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='proxy_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tracker_type',
            field=models.CharField(blank=True, default='zeustrak', max_length=32, null=True, verbose_name='Трекер'),
        ),
    ]
