# Generated by Django 2.2.9 on 2019-12-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_auto_20191218_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountImage',
        ),
    ]
