# Generated by Django 2.2.9 on 2019-12-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_delete_accountimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-username',)},
        ),
    ]
