# Generated by Django 2.2.9 on 2019-12-20 09:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0127_auto_20191219_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('actor_repr', models.CharField(max_length=255, verbose_name='Actor repr')),
                ('verb', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('target_repr', models.CharField(max_length=255, verbose_name='Target repr')),
                ('action_object_object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('action_repr', models.CharField(max_length=255, verbose_name='Action repr')),
                ('action_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('action_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_object', to='contenttypes.ContentType')),
                ('actor_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actor', to='contenttypes.ContentType')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('-action_datetime',),
            },
        ),
    ]
