# Generated by Django 2.2.9 on 2019-12-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_auto_20191220_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_repr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Action repr'),
        ),
        migrations.AlterField(
            model_name='action',
            name='target_repr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target repr'),
        ),
    ]
