# Generated by Django 2.2.9 on 2019-12-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_auto_20191220_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action_repr',
        ),
        migrations.AddField(
            model_name='action',
            name='action_object_repr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Action object repr'),
        ),
    ]
