# Generated by Django 2.2.9 on 2019-12-23 07:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0134_auto_20191220_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='action',
            name='target_content_type',
        ),
        migrations.AddField(
            model_name='action',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Additional data'),
        ),
        migrations.AddField(
            model_name='action',
            name='target_object_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_object', to='contenttypes.ContentType'),
        ),
    ]
