# Generated by Django 2.2.9 on 2019-12-23 07:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_auto_20191223_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Additional action data'),
        ),
    ]
