# Generated by Django 2.2.9 on 2019-12-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_auto_20191223_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='target_repr',
            new_name='target_object_repr',
        ),
    ]
