# Generated by Django 2.2.9 on 2019-12-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_remove_tag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='description',
        ),
        migrations.AddField(
            model_name='action',
            name='verb_slug',
            field=models.SlugField(default='verb', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.CharField(max_length=255),
        ),
    ]
