# Generated by Django 2.2.9 on 2019-12-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_auto_20191224_0917'),
        ('core', '0125_contact_comment'),
    ]

    operations = [
    ]
