# Generated by Django 2.2.9 on 2019-12-24 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_merge_20191224_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(choices=[(100, 'New'), (0, 'Active'), (20, 'Banned'), (10, 'Logged out'), (30, 'On verification'), (40, 'Inactive'), (50, 'Surfing'), (60, 'Warming'), (65, 'Setup'), (70, 'Ready to use')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
        ),
    ]
