# Generated by Django 2.2.9 on 2019-12-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_auto_20191224_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundrequest',
            name='date',
        ),
    ]
