# Generated by Django 2.2.9 on 2019-12-24 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_remove_fundrequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundrequest',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='fundrequest',
            name='processed_user',
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funds_processed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funds', to='core.Account'),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Waiting'), (20, 'Declined'), (50, 'Approve')], default=0, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
