# Generated by Django 2.2.9 on 2019-12-24 13:42

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_auto_20191224_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequest',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Waiting'), (20, 'Declined'), (50, 'Approve')], default=0, verbose_name='Request status'),
        ),
    ]
