# Generated by Django 2.2.9 on 2019-12-24 18:10
from django.core.serializers.json import DjangoJSONEncoder

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_auto_20191224_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatuslog',
            name='end_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountstatuslog',
            name='start_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=DjangoJSONEncoder, null=True, verbose_name='Additional action data'),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_requests', to='core.Account'),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Funded datetime'),
        ),
        migrations.AlterIndexTogether(
            name='accountstatuslog',
            index_together={('start_at', 'end_at')},
        ),
    ]
