# Generated by Django 2.2.9 on 2019-12-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_auto_20191224_1810'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='accountstatuslog',
            index_together={('start_at', 'end_at'), ('account', 'status')},
        ),
    ]
