# Generated by Django 2.2.9 on 2019-12-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_auto_20191224_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterField(
            model_name='accountstatuslog',
            name='status',
            field=models.PositiveIntegerField(choices=[(100, 'New'), (0, 'Active'), (20, 'Banned'), (10, 'Logged out'), (30, 'On verification'), (40, 'Inactive'), (50, 'Surfing'), (60, 'Warming'), (65, 'Setup'), (70, 'Ready to use')], db_index=True),
        ),
    ]
