# Generated by Django 2.2.9 on 2019-12-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_auto_20191224_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(default='UA', max_length=2),
        ),
    ]
