# Generated by Django 2.2.9 on 2019-12-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_account_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mla_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Multiloginapp profile ID'),
        ),
    ]
