# Generated by Django 2.2.9 on 2019-12-25 10:33
from django.core.serializers.json import DjangoJSONEncoder

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_account_mla_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='mla_uuid',
            new_name='mla_profile_id',
        ),
        migrations.AddField(
            model_name='account',
            name='mla_profile_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=DjangoJSONEncoder, null=True, verbose_name='Multiloginapp profile data'),
        ),
    ]
