# Generated by Django 2.2.9 on 2019-12-25 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_auto_20191225_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrequest',
            name='processed_user',
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_processed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Waiting'), (20, 'Declined'), (50, 'Done')], default=0, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Funded datetime'),
        ),
    ]
