# Generated by Django 2.2.9 on 2019-12-25 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_auto_20191225_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundrequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Waiting'), (20, 'Declined'), (50, 'Approve')], default=0, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_account_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_fund_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
