# Generated by Django 2.2.9 on 2019-12-25 13:39

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_auto_20191225_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mla_profile_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Multiloginapp profile data'),
        ),
        migrations.AlterField(
            model_name='action',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Additional action data'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('accounts_request_create', 'Accs request create'), ('accounts_request_approved', 'Accs request approved'), ('accounts_request_declined', 'Accs request approved'), ('funds_create', 'Funds request create'), ('funds_declined', 'Funds request declined'), ('funds_approved', 'Funds request approved'), ('account_changed', 'Account changed')], default='funds', max_length=64, verbose_name='Notification type'),
        ),
    ]
