# Generated by Django 2.2.9 on 2019-12-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_auto_20191225_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
    ]
