# Generated by Django 2.2.9 on 2019-12-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_auto_20191226_0718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('-created_at',)},
        ),
    ]
