# Generated by Django 2.2.9 on 2019-12-27 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_auto_20191226_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='operate_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
