# Generated by Django 2.2.9 on 2019-12-27 09:03

from django.db import migrations

def fill_operate_by(apps, *args, **kwargs):
    Account = apps.get_model('core', 'Account')
    for account in Account.objects.all():
        account.operate_by = account.owner
        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_account_operate_by'),
    ]

    operations = [
        migrations.RunPython(fill_operate_by),
    ]
