# Generated by Django 2.2.9 on 2020-01-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_auto_20191227_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'info'), (10, 'warning'), (20, 'critical')], default=0, verbose_name='Notification level'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('account', 'account'), ('funds', 'funds')], default='account', max_length=64, verbose_name='Notification type'),
        ),
    ]
