# Generated by Django 2.2.9 on 2020-01-02 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_auto_20200102_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='operate_by',
        ),
        migrations.RemoveField(
            model_name='fieldssetting',
            name='action',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='account',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managing_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('account', 'account'), ('funds', 'funds')], default='account', max_length=64, verbose_name='Notification category'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(100, 'New'), (0, 'Active'), (20, 'Banned'), (10, 'Logged out'), (30, 'On verification'), (40, 'Inactive'), (50, 'Surfing'), (60, 'Warming'), (65, 'Setup'), (70, 'Ready to use')], default=100, protected=True, verbose_name='Account status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
