# Generated by Django 2.2.9 on 2020-01-03 08:44

from django.db import migrations
from django.db.models import F


def fill_manager(apps, *args, **kwargs):
    Account = apps.get_model('core', 'Account')
    for account in Account.objects.all():
        account.manager_id = F('owner_id')
        account.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_auto_20200102_1354'),
    ]

    operations = [
        migrations.RunPython(fill_manager),
    ]
