# Generated by Django 2.2.9 on 2020-01-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_auto_20200103_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_funds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Account funds'),
        ),
    ]
