# Generated by Django 2.2.9 on 2020-01-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_auto_20200103_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsubscription',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'info'), (10, 'warning'), (20, 'critical')], verbose_name='Notification level'),
        ),
    ]
