# Generated by Django 2.2.9 on 2020-01-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_auto_20200104_0840'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationsubscription',
            unique_together={('user', 'level', 'channel')},
        ),
    ]
