# Generated by Django 2.2.9 on 2020-01-04 09:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_auto_20200104_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='BM name')),
                ('business_id', models.BigIntegerField(verbose_name='BM id')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), blank=True, db_index=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='adaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.BusinessManager'),
        ),
        migrations.AddField(
            model_name='businessmanager',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='core.Account'),
        ),
    ]
