# Generated by Django 2.2.9 on 2020-01-04 09:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion

def clear_user_id(apps, *args, **kwargs):
    AdAccount = apps.get_model('core', 'AdAccount')
    AdAccount.objects.all().update(user_id=None)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_auto_20200104_0845'),
    ]

    operations = [
        migrations.RunPython(clear_user_id),
    ]
