# Generated by Django 2.2.9 on 2020-01-04 09:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_auto_20200104_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.User'),
        ),
    ]
