# Generated by Django 2.2.9 on 2020-01-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_auto_20200104_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adaccount',
            old_name='user',
            new_name='business',
        ),
        migrations.RunSQL(
            "DROP INDEX IF EXISTS core_adaccount_user_id_d9965f0b",
        )
    ]
