# Generated by Django 2.2.9 on 2020-01-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_auto_20200106_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=32, unique=True, verbose_name='Setting key')),
                ('value', models.CharField(max_length=255, verbose_name='Setting value')),
                ('value_type', models.CharField(choices=[('str', 'String'), ('float', 'Float'), ('int', 'Integer'), ('bool', 'Boolean')], default='str', max_length=10, verbose_name='Value type')),
                ('verbose_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Verbose name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Usefull description')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
