# Generated by Django 2.2.9 on 2020-01-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_config'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Config',
            new_name='CRMConfig',
        ),
    ]
