# Generated by Django 2.2.9 on 2020-01-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_auto_20200107_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CRMConfig',
            new_name='Config',
        ),
    ]
