# Generated by Django 2.2.9 on 2020-01-08 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_userrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountstatuslog',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Account'),
        ),
    ]
