# Generated by Django 2.2.9 on 2020-01-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_auto_20200108_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sended_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sended_telegram_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
