# Generated by Django 2.2.9 on 2020-01-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_auto_20200108_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='tracker_spends',
        ),
        migrations.AlterField(
            model_name='ad',
            name='effective_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DELETED', 'Deleted'), ('PENDING_REVIEW', 'Pending_review'), ('DISAPPROVED', 'Disapproved'), ('PREAPPROVED', 'Preapproved'), ('PENDING_BILLING_INFO', 'Pending_billing_info'), ('CAMPAIGN_PAUSED', 'Campaign_paused'), ('ARCHIVED', 'Archived'), ('ADSET_PAUSED', 'Adset_paused'), ('IN_PROCESS', 'In_process'), ('WITH_ISSUES', 'With_issues')], default='ACTIVE', max_length=24, verbose_name='Ad effective status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('account', 'account'), ('funds', 'funds'), ('request', 'request')], default='account', max_length=64, verbose_name='Notification category'),
        ),
    ]
