# Generated by Django 2.2.9 on 2020-01-08 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_auto_20200108_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatuslog',
            name='log_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Status'), (1, 'Manager')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='accountstatuslog',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountstatuslog',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(100, 'New'), (0, 'Active'), (20, 'Banned'), (10, 'Logged out'), (30, 'On verification'), (40, 'Inactive'), (50, 'Surfing'), (60, 'Warming'), (65, 'Setup'), (70, 'Ready to use')], db_index=True, null=True),
        ),
    ]
