# Generated by Django 2.2.9 on 2020-01-09 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_auto_20200108_1938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountStatusLog',
            new_name='AccountLog',
        ),
    ]
