# Generated by Django 2.2.9 on 2020-01-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_auto_20200109_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tracker domain'),
        ),
    ]
