# Generated by Django 2.2.9 on 2020-01-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_account_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='is_personal',
            field=models.BooleanField(default=False, verbose_name='IS personal'),
        ),
    ]
