# Generated by Django 2.2.9 on 2020-01-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_adaccount_is_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaccount',
            name='is_personal',
        ),
    ]
