# Generated by Django 2.2.9 on 2020-01-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_remove_adaccount_is_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='max_billing_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='max_billing_threshold'),
        ),
    ]
