# Generated by Django 2.2.9 on 2020-01-10 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_adaccount_max_billing_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmanager',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
    ]
