# Generated by Django 2.2.9 on 2020-01-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_businessmanager_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaccount',
            name='disable_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, None), (1, 'Ads integrity policy'), (2, 'Ads ip review'), (3, 'Risk payment'), (4, 'Gray account shut down'), (5, 'Ads afc review'), (6, 'Business integrity rar'), (7, 'Permanent close'), (8, 'Unused reseller account'), (9, 'Unused account')], default=0, null=True, verbose_name='Ad account disable reason'),
        ),
        migrations.AlterField(
            model_name='adaccount',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Disabled'), (3, 'Unsettled'), (7, 'Pending risk review'), (8, 'Pending settlement'), (9, 'In grace period'), (100, 'Pending closure'), (101, 'Closed'), (201, 'Any active'), (202, 'Any closed')], default=1, verbose_name='Ad account status'),
        ),
    ]
