# Generated by Django 2.2.9 on 2020-01-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_auto_20200110_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Comment'),
        ),
    ]
