# Generated by Django 2.2.9 on 2020-01-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0186_account_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterIndexTogether(
            name='action',
            index_together={('action_object_content_type', 'action_object_object_id'), ('target_object_content_type', 'target_object_id')},
        ),
    ]
