# Generated by Django 2.2.9 on 2020-01-15 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_auto_20200113_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='AdAccountLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, 'Active'), (2, 'Disabled'), (3, 'Unsettled'), (7, 'Pending risk review'), (8, 'Pending settlement'), (9, 'In grace period'), (100, 'Pending closure'), (101, 'Closed'), (201, 'Any active'), (202, 'Any closed')], db_index=True, null=True)),
                ('adaccount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.AdAccount')),
            ],
            options={
                'index_together': {('adaccount', 'status'), ('start_at', 'end_at')},
            },
        ),
    ]
