# Generated by Django 2.2.9 on 2020-01-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_auto_20200115_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='data',
            new_name='request_data',
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('account', 'account'), ('adaccount', 'adaccount'), ('funds', 'funds'), ('request', 'request')], default='account', max_length=64, verbose_name='Notification category'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='request_type',
            field=models.CharField(choices=[('accounts', 'Accounts request'), ('money', 'Money request'), ('setup', 'Setup request'), ('fix', 'Fix request')], default='topup', max_length=32, verbose_name='Request type'),
        ),
    ]
