# Generated by Django 2.2.9 on 2020-01-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0189_auto_20200117_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlog',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
