# Generated by Django 2.2.9 on 2020-01-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0193_auto_20200122_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaccountdaystat',
            name='user',
        ),
        migrations.AlterField(
            model_name='account',
            name='fb_spends',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Account Total FB spends'),
        ),
        migrations.AlterField(
            model_name='adaccountstat',
            name='spend_diff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Spend diff'),
        ),
    ]
