# Generated by Django 2.2.9 on 2020-01-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_auto_20200123_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='fb_balance',
        ),
        migrations.AlterField(
            model_name='account',
            name='fb_spends',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Account FB spends'),
        ),
    ]
