# Generated by Django 2.2.9 on 2020-01-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_auto_20200123_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDayStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visits')),
                ('leads', models.PositiveIntegerField(default=0, verbose_name='Leads')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Account')),
            ],
        ),
    ]
