# Generated by Django 2.2.9 on 2020-01-24 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_accountdaystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='campaigndaystat',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.PositiveIntegerField()),
                ('campaign_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=2)),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visits')),
                ('leads', models.PositiveIntegerField(default=0, verbose_name='Leads')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='campaigndaystat',
            name='campaign_id',
        ),
        migrations.RemoveField(
            model_name='campaigndaystat',
            name='campaign_name',
        ),
        migrations.RemoveField(
            model_name='campaigndaystat',
            name='command',
        ),
        migrations.RemoveField(
            model_name='campaigndaystat',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='campaigndaystat',
            name='user',
        ),
    ]
