# Generated by Django 2.2.9 on 2020-01-24 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_auto_20200124_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndaystat',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Campaign'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigndaystat',
            unique_together={('campaign', 'date')},
        ),
    ]
