# Generated by Django 2.2.9 on 2020-01-24 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0198_auto_20200124_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visits_diff', models.PositiveIntegerField(default=0, verbose_name='Visits')),
                ('leads_diff', models.PositiveIntegerField(default=0, verbose_name='Leads')),
                ('clicks_diff', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('revenue_diff', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue')),
                ('cost_diff', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost')),
                ('profit_diff', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
