# Generated by Django 2.2.9 on 2020-01-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0200_campaignstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='visits',
        ),
        migrations.AlterField(
            model_name='config',
            name='value_type',
            field=models.CharField(choices=[('str', 'String'), ('float', 'Float'), ('int', 'Integer'), ('dict', 'Dict'), ('bool', 'Boolean')], default='str', max_length=10, verbose_name='Value type'),
        ),
    ]
