# Generated by Django 2.2.9 on 2020-01-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0202_auto_20200127_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignuserdatestat',
            name='clicks_diff',
            field=models.PositiveIntegerField(default=0, verbose_name='Clicks diff'),
        ),
        migrations.AlterField(
            model_name='campaignuserdatestat',
            name='cost_diff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost diff'),
        ),
        migrations.AlterField(
            model_name='campaignuserdatestat',
            name='leads_diff',
            field=models.PositiveIntegerField(default=0, verbose_name='Leads diff'),
        ),
        migrations.AlterField(
            model_name='campaignuserdatestat',
            name='profit_diff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit diff'),
        ),
        migrations.AlterField(
            model_name='campaignuserdatestat',
            name='revenue_diff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue diff'),
        ),
        migrations.AlterField(
            model_name='campaignuserdatestat',
            name='visits_diff',
            field=models.PositiveIntegerField(default=0, verbose_name='Visits diff'),
        ),
    ]
