# Generated by Django 2.2.9 on 2020-01-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0203_auto_20200127_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdaystat',
            name='processed_accounts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Accounts ready'),
        ),
        migrations.AddField(
            model_name='userdaystat',
            name='processed_requests',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total Processed requests'),
        ),
        migrations.AddField(
            model_name='userdaystat',
            name='total_accs',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total accs on current date'),
        ),
        migrations.AlterField(
            model_name='userdaystat',
            name='banned_accs',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Banned accs on date'),
        ),
        migrations.AlterUniqueTogether(
            name='userdaystat',
            unique_together={('user', 'date')},
        ),
        migrations.RemoveField(
            model_name='userdaystat',
            name='active_accs',
        ),
        migrations.RemoveField(
            model_name='userdaystat',
            name='command',
        ),
    ]
