# Generated by Django 2.2.9 on 2020-01-28 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0204_auto_20200128_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignuserdatestat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 9, 6, 20, 42364, tzinfo=utc)),
        ),
    ]
