# Generated by Django 2.2.9 on 2020-01-28 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0205_auto_20200128_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignuserdatestat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
