# Generated by Django 2.2.9 on 2020-01-28 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0206_auto_20200128_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Account'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='adaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.AdAccount'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.FBPage'),
        ),
        migrations.AlterField(
            model_name='adaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adaccounts', to='core.Account'),
        ),
        migrations.AlterField(
            model_name='adaccountdaystat',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Account'),
        ),
        migrations.AlterField(
            model_name='adaccountdaystat',
            name='adaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.AdAccount'),
        ),
        migrations.AlterField(
            model_name='adaccountstat',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Account'),
        ),
        migrations.AlterField(
            model_name='adaccountstat',
            name='adaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.AdAccount'),
        ),
        migrations.AlterField(
            model_name='adaccountstat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fbpage',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Account'),
        ),
        migrations.AlterField(
            model_name='fieldssetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdaystat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
