# Generated by Django 2.2.9 on 2020-01-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0207_auto_20200128_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profit_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monthly Profit target'),
        ),
    ]
