# Generated by Django 2.2.9 on 2020-01-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0208_user_profit_target'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDayStat',
            new_name='UserDateStat',
        ),
    ]
