# Generated by Django 2.2.9 on 2020-01-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0209_auto_20200128_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='flow_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='flow_name',
            field=models.CharField(default='FLOW', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='status',
            field=models.CharField(default='active', max_length=64),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FlowDayStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visits')),
                ('leads', models.PositiveIntegerField(default=0, verbose_name='Leads')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Flow')),
            ],
            options={
                'unique_together': {('flow', 'date')},
            },
        ),
    ]
