# Generated by Django 2.2.9 on 2020-01-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0210_auto_20200128_1339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDateStat',
            new_name='UserDayStat',
        ),
    ]
