# Generated by Django 2.2.9 on 2020-01-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0211_auto_20200128_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowdaystat',
            name='cpv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flowdaystat',
            name='cr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flowdaystat',
            name='ctr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flowdaystat',
            name='cv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flowdaystat',
            name='epc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flowdaystat',
            name='epv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flowdaystat',
            name='roi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
