# Generated by Django 2.2.9 on 2020-01-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0212_auto_20200128_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Config', 'verbose_name_plural': 'Config'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
