# Generated by Django 2.2.9 on 2020-01-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0213_auto_20200129_0821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdAccountStat',
            new_name='AdAccountUserStat',
        ),
        migrations.AddField(
            model_name='account',
            name='funds_wait',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Account funds wait'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_funded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Account last topup'),
        ),
    ]
