# Generated by Django 2.2.9 on 2020-01-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0214_auto_20200129_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdaystat',
            name='spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Spend'),
        ),
        migrations.AlterField(
            model_name='userdaystat',
            name='banned_accs',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Banned accs'),
        ),
    ]
