# Generated by Django 2.2.9 on 2020-01-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0215_auto_20200130_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.TextField(verbose_name='Setting value'),
        ),
    ]
