# Generated by Django 2.2.9 on 2020-02-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0216_auto_20200130_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mla_login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('account', 'account'), ('adaccount', 'adaccount'), ('request', 'request')], default='account', max_length=64, verbose_name='Notification category'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='request_type',
            field=models.CharField(choices=[('accounts', 'Accounts request'), ('money', 'Money request'), ('setup', 'Setup request'), ('fix', 'Fix request')], default='money', max_length=32, verbose_name='Request type'),
        ),
    ]
