# Generated by Django 2.2.9 on 2020-02-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0217_auto_20200205_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Comment'),
        ),
    ]
