# Generated by Django 2.2.10 on 2020-02-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0219_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='effective_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DELETED', 'Deleted'), ('PENDING_REVIEW', 'Pending review'), ('DISAPPROVED', 'Disapproved'), ('PREAPPROVED', 'Preapproved'), ('PENDING_BILLING_INFO', 'Pending billing info'), ('CAMPAIGN_PAUSED', 'Campaign paused'), ('ARCHIVED', 'Archived'), ('ADSET_PAUSED', 'Adset paused'), ('IN_PROCESS', 'In process'), ('WITH_ISSUES', 'With issues')], default='ACTIVE', max_length=24, verbose_name='Ad effective status'),
        ),
    ]
