# Generated by Django 2.2.10 on 2020-02-07 07:31

from django.db import migrations


def migrate_accs_names(apps, *args, **kwargs):
    Account = apps.get_model('core', 'Account')
    accounts = Account.objects.all().exclude(status=20).order_by('-id')
    for account in accounts:
        if not account.id == 2:
            country, id = account.name.replace('  ', ' ').split(' ')[0:2]
            print(country, id, account.id, account.name)
            account.country_code = country.strip().upper()
            account.comment = account.name
            account.id = int(id.strip()[:3])
            account.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0220_auto_20200206_1124'),
    ]

    operations = [
        migrations.RunPython(migrate_accs_names),
    ]
