# Generated by Django 2.2.9 on 2020-02-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0221_auto_20200207_0731'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdaystat',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='accountlog',
            index_together={('start_at', 'end_at'), ('account', 'status', 'log_type', 'end_at')},
        ),
    ]
