# Generated by Django 2.2.9 on 2020-02-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0222_auto_20200210_1158'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdaystat',
            unique_together={('user', 'date')},
        ),
    ]
