# Generated by Django 2.2.9 on 2020-02-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0223_auto_20200210_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='proxy_login',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='proxy_password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='proxy_login',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='proxy_password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
