# Generated by Django 2.2.9 on 2020-02-10 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0224_auto_20200210_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReuestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.PositiveIntegerField(blank=True, choices=[(0, 'Waiting'), (20, 'Declined'), (50, 'Approve')], db_index=True, null=True)),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.UserRequest')),
            ],
            options={
                'index_together': {('user_request', 'status'), ('start_at', 'end_at')},
            },
        ),
    ]
