# Generated by Django 2.2.9 on 2020-02-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0225_userreuestlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReuestLog',
            new_name='UserRequestLog',
        ),
    ]
