# Generated by Django 2.2.10 on 2020-02-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0226_auto_20200210_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('sort',), 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='owner',
        ),
    ]
