# Generated by Django 2.2.10 on 2020-02-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0227_auto_20200211_0539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CampaignUserDateStat',
            new_name='CampaignUserDayStat',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
