# Generated by Django 2.2.10 on 2020-02-11 10:02

from django.db import migrations

def empty_account_proxy(apps, *args, **kwargs):
    Account = apps.get_model('core', 'Account')
    Account.objects.all().update(proxy_login=None, proxy_password=None, proxy_port=None, proxy_host=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0228_auto_20200211_0912'),
    ]

    operations = [
        migrations.RunPython(empty_account_proxy),
    ]
