# Generated by Django 2.2.10 on 2020-02-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0229_auto_20200211_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='adaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AdAccount'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FBPage'),
        ),
    ]
