# Generated by Django 2.2.10 on 2020-02-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0230_auto_20200211_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Ad name'),
        ),
        migrations.AlterField(
            model_name='adaccountdaystat',
            name='adaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AdAccount'),
        ),
        migrations.AlterField(
            model_name='adaccountlog',
            name='adaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AdAccount'),
        ),
        migrations.AlterField(
            model_name='adaccountuserstat',
            name='adaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AdAccount'),
        ),
        migrations.AlterField(
            model_name='userrequestlog',
            name='user_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserRequest'),
        ),
    ]
