# Generated by Django 2.2.10 on 2020-02-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0231_auto_20200211_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(default='archived', max_length=32),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tracking_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='campaigndaystat',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Campaign'),
        ),
        migrations.AlterField(
            model_name='campaignuserdaystat',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Campaign'),
        ),
    ]
