# Generated by Django 2.2.10 on 2020-02-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0232_auto_20200212_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='campaign_id',
            new_name='old_campaign_id',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign_name',
            new_name='name',
        ),
    ]
