# Generated by Django 2.2.10 on 2020-02-12 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0233_auto_20200212_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Campaign'),
        ),
    ]
