# Generated by Django 2.2.10 on 2020-02-12 10:50

from django.db import migrations

def fill_campaign(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Campaign = apps.get_model("core", "Campaign")
    Account = apps.get_model("core", "Account")
    db_alias = schema_editor.connection.alias
    accounts = Account.objects.using(db_alias).filter(old_campaign_id__isnull=False)
    for account in accounts:
        campaign = Campaign.objects.using(db_alias).filter(campaign_id=account.old_campaign_id).first()
        if campaign:
            account.campaign=campaign
            account.save(update_fields=['campaign'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0234_account_campaign'),
    ]

    operations = [
        migrations.RunPython(fill_campaign),
    ]
