# Generated by Django 2.2.10 on 2020-02-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0235_auto_20200212_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='old_campaign_id',
        ),
    ]
