# Generated by Django 2.2.10 on 2020-02-12 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0236_remove_account_old_campaign_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaccount',
            name='campaign_id',
        ),
        migrations.AddField(
            model_name='adaccount',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Campaign'),
        ),
    ]
