# Generated by Django 2.2.10 on 2020-02-17 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0237_auto_20200212_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('account', 'account'), ('adaccount', 'adaccount'), ('request', 'request'), ('ad', 'ad')], default='account', max_length=64, verbose_name='Notification category'),
        ),
        migrations.AlterUniqueTogether(
            name='ad',
            unique_together={('adaccount', 'ad_id', 'creative_id')},
        ),
        migrations.RemoveField(
            model_name='ad',
            name='account',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='is_deleted',
        ),
    ]
