# Generated by Django 2.2.10 on 2020-02-17 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0238_auto_20200217_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
