# Generated by Django 2.2.10 on 2020-02-17 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0239_accountlog_changed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('log_type', models.PositiveSmallIntegerField(choices=[(0, 'Status'), (1, 'Manager')], db_index=True, default=0)),
                ('status', models.PositiveIntegerField(blank=True, choices=[(100, 'New'), (0, 'Active'), (20, 'Banned'), (10, 'Logged out'), (30, 'On verification'), (40, 'Inactive'), (50, 'Surfing'), (60, 'Warming'), (65, 'Setup'), (70, 'Ready to use')], db_index=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Campaign')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_logs', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'index_together': {('start_at', 'end_at'), ('campaign', 'status', 'log_type', 'end_at')},
            },
        ),
    ]
