# Generated by Django 2.2.10 on 2020-02-18 09:46

from django.db import migrations
from django.utils import timezone


def fill_manager_log(apps, *args, **kwargs):
    Campaign = apps.get_model('core', 'Campaign')
    CampaignLog = apps.get_model('core', 'CampaignLog')
    now = timezone.now()
    for campaign in Campaign.objects.all():
        CampaignLog.objects.create(
            campaign=campaign,
            start_at=now,
            log_type=1,  # Manager
            manager=campaign.user,
            changed_by=None,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0240_campaignlog'),
    ]

    operations = [
        migrations.RunPython(fill_manager_log),
    ]
