# Generated by Django 2.2.10 on 2020-02-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0241_auto_20200218_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignlog',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
