# Generated by Django 2.2.10 on 2020-02-25 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0244_businessmanager_shared_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='core.Campaign'),
        ),
        migrations.AlterField(
            model_name='adaccount',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adaccounts', to='core.Campaign'),
        ),
        migrations.CreateModel(
            name='DayStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visits')),
                ('leads', models.PositiveIntegerField(default=0, verbose_name='Leads')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue')),
                ('spends', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='FB Spends')),
                ('funds', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Funds')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit')),
                ('profit_correction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit Corrections')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Account')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'user', 'account', 'campaign')},
            },
        ),
    ]
