# Generated by Django 2.2.10 on 2020-02-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0245_auto_20200225_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='daystat',
            name='adaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.AdAccount'),
        ),
        migrations.AlterUniqueTogether(
            name='daystat',
            unique_together={('date', 'user', 'account', 'adaccount', 'campaign')},
        ),
    ]
