# Generated by Django 2.2.10 on 2020-02-26 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0247_auto_20200225_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCampaignDayStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visits')),
                ('leads', models.PositiveIntegerField(default=0, verbose_name='Leads')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit')),
                ('spends', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='spends')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdAccountDayStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Spend')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Account')),
                ('adaccount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.AdAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
