# Generated by Django 2.2.10 on 2020-02-26 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0248_useradaccountdaystat_usercampaigndaystat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercampaigndaystat',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='usercampaigndaystat',
            name='spends',
        ),
    ]
