# Generated by Django 2.2.10 on 2020-02-27 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0249_auto_20200226_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='active_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='banned_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='account',
            name='logout_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='prev_status',
        ),
        migrations.RemoveField(
            model_name='account',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='account',
            name='surfing_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='warming_at',
        ),
    ]
