# Generated by Django 2.2.10 on 2020-02-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0250_auto_20200227_0601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountRequest',
        ),
    ]
