# Generated by Django 2.2.10 on 2020-02-27 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0251_delete_accountrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradaccountdaystat',
            name='clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='clicks'),
        ),
        migrations.AddField(
            model_name='usercampaigndaystat',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='usercampaigndaystat',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit'),
        ),
        migrations.AlterField(
            model_name='usercampaigndaystat',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usercampaigndaystat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useradaccountdaystat',
            unique_together={('date', 'account', 'adaccount', 'user')},
        ),
        migrations.CreateModel(
            name='UserAccountDayStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Spend')),
                ('funds', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Funds')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visits')),
                ('leads', models.PositiveIntegerField(default=0, verbose_name='Leads')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Account')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
