# Generated by Django 2.2.10 on 2020-02-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0252_auto_20200227_1339'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useradaccountdaystat',
            unique_together=set(),
        ),
    ]
