# Generated by Django 2.2.10 on 2020-02-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0253_auto_20200227_1415'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE UNIQUE INDEX date_acc_adacc_user_id ON core_useradaccountdaystat (date, account_id, adaccount_id, COALESCE(user_id, -1))",
        )
    ]
