# Generated by Django 2.2.10 on 2020-02-27 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0254_auto_20200227_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradaccountdaystat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
