# Generated by Django 2.2.10 on 2020-02-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0255_auto_20200227_1450'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE UNIQUE INDEX date_camp_user_id ON core_usercampaigndaystat (date, campaign_id, COALESCE(user_id, -1))"
        )
    ]
