# Generated by Django 2.2.10 on 2020-02-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0257_auto_20200228_1039'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE UNIQUE INDEX date_acc_camp_user_id_unique ON core_useraccountdaystat (date, COALESCE(account_id, -1), COALESCE(campaign_id, -1), COALESCE(user_id, -1))"
        )
    ]
