# Generated by Django 2.2.10 on 2020-02-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0259_auto_20200228_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountdaystat',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost'),
        ),
    ]
