# Generated by Django 2.2.10 on 2020-03-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0261_auto_20200301_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='disable_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flowdaystat',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
