# Generated by Django 2.2.10 on 2020-03-01 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0262_auto_20200301_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='core.FBPage'),
        ),
    ]
