# Generated by Django 2.2.10 on 2020-03-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0263_auto_20200301_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
