# Generated by Django 2.2.10 on 2020-03-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0264_auto_20200311_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Admin'), (10, 'Mediabuyer'), (20, 'Financier'), (30, 'Farmer'), (40, 'Supplier'), (50, 'Setuper'), (60, 'Manager')], default=10, verbose_name='User role'),
        ),
    ]
