# Generated by Django 2.2.10 on 2020-03-13 09:46

from django.db import migrations
from django.db.models import F


def fill_supplier(apps, *args, **kwargs):
    Account = apps.get_model('core', 'Account')
    for account in Account.objects.all():
        acc = Account.objects.select_for_update().get(id=account.id)
        acc.supplier_id = F('created_by_id')
        acc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0266_account_supplier'),
    ]

    operations = [
        migrations.RunPython(fill_supplier),
    ]
