# Generated by Django 2.2.10 on 2020-03-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0268_auto_20200313_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradaccountdaystat',
            name='clicks',
            field=models.IntegerField(default=0, verbose_name='clicks'),
        ),
    ]
