# Generated by Django 2.2.10 on 2020-03-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0269_auto_20200321_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Ad URL'),
        ),
    ]
