# Generated by Django 2.2.10 on 2020-03-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0270_ad_ad_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
    ]
