# Generated by Django 2.2.10 on 2020-03-25 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0272_accountactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountactivitylog',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Session UUID'),
        ),
    ]
