# Generated by Django 2.2.10 on 2020-03-26 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0273_accountactivitylog_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Unknown'), (0, 'Male'), (1, 'Female')], null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='referer',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date added'),
        ),
    ]
