# Generated by Django 2.2.11 on 2020-04-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0274_auto_20200326_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='total_spends',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Account full spends'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('account', 'account'), ('adaccount', 'adaccount'), ('request', 'request'), ('ad', 'ad'), ('finance', 'finance')], default='account', max_length=64, verbose_name='Notification category'),
        ),
        migrations.DeleteModel(
            name='AccountDayStat',
        ),
    ]
