# Generated by Django 2.2.11 on 2020-04-07 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0275_auto_20200406_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(default='profit', max_length=32)),
                ('value', models.PositiveIntegerField()),
                ('start_at', models.DateField(db_index=True)),
                ('end_at', models.DateField(db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='daystat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='daystat',
            name='account',
        ),
        migrations.RemoveField(
            model_name='daystat',
            name='adaccount',
        ),
        migrations.RemoveField(
            model_name='daystat',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='daystat',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userdaystat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userdaystat',
            name='user',
        ),
        migrations.DeleteModel(
            name='CampaignUserDayStat',
        ),
        migrations.DeleteModel(
            name='DayStat',
        ),
        migrations.DeleteModel(
            name='UserDayStat',
        ),
    ]
