# Generated by Django 2.2.11 on 2020-04-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0276_auto_20200407_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkpi',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
