# Generated by Django 2.2.11 on 2020-04-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0277_auto_20200407_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkpi',
            name='value',
            field=models.PositiveIntegerField(),
        ),
    ]
