# Generated by Django 2.2.11 on 2020-04-09 13:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0278_auto_20200407_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdAccountTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='Billing start time')),
                ('end_at', models.DateTimeField(db_index=True, verbose_name='Billing end time')),
                ('billed_at', models.DateTimeField(db_index=True, verbose_name='Billed at')),
                ('reason', models.CharField(max_length=1024, verbose_name='Billing reason')),
                ('charge_type', models.CharField(max_length=32, verbose_name='charge_type')),
                ('product_type', models.CharField(max_length=32, verbose_name='product_type')),
                ('payment_option', models.CharField(max_length=32, verbose_name='payment_option')),
                ('status', models.CharField(max_length=32, verbose_name='payment_option')),
                ('tracking_id', models.CharField(max_length=32, verbose_name='tracking_id')),
                ('transaction_type', models.CharField(max_length=32, verbose_name='transaction_type')),
                ('vat_invoice_id', models.CharField(max_length=32, verbose_name='transaction_type')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='RAW transaction data')),
                ('adaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AdAccount')),
            ],
        ),
        migrations.DeleteModel(
            name='FundRequest',
        ),
    ]
