# Generated by Django 2.2.11 on 2020-04-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0279_auto_20200409_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaccounttransaction',
            name='product_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='product_type'),
        ),
        migrations.AlterField(
            model_name='adaccounttransaction',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='tracking_id'),
        ),
        migrations.AlterField(
            model_name='adaccounttransaction',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='transaction_type'),
        ),
        migrations.AlterField(
            model_name='adaccounttransaction',
            name='vat_invoice_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='transaction_type'),
        ),
    ]
