# Generated by Django 2.2.11 on 2020-04-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0280_auto_20200409_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaccount',
            name='max_billing_threshold',
        ),
        migrations.AddField(
            model_name='adaccount',
            name='payment_cycle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Payment cycle'),
        ),
    ]
