# Generated by Django 3.0.5 on 2020-04-13 09:43

from django.db import migrations
from django.utils import timezone


def fill_card_log(apps, *args, **kwargs):
    Account = apps.get_model('core', 'Account')
    AccountLog = apps.get_model('core', 'AccountLog')
    accounts = Account.objects.all()
    now = timezone.now()
    for account in accounts:
        if account.card_number:
            AccountLog.objects.create(
                account=account,
                start_at=now,
                log_type=2,
                card_number=account.card_number,
            )



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0283_auto_20200413_0942'),
    ]

    operations = [
        migrations.RunPython(fill_card_log),
    ]
