# Generated by Django 3.0.5 on 2020-04-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0285_adaccount_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaccount',
            name='limit',
        ),
    ]
