# Generated by Django 3.0.5 on 2020-04-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0286_remove_adaccount_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Day spends limit'),
        ),
    ]
