# Generated by Django 3.0.5 on 2020-04-16 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0287_adaccount_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
