# Generated by Django 3.0.5 on 2020-04-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0289_auto_20200416_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='adaccount',
            name='timezone_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Timezone name'),
        ),
        migrations.AddField(
            model_name='adaccount',
            name='timezone_offset_hours_utc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
