# Generated by Django 3.0.5 on 2020-04-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0290_auto_20200417_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmanager',
            name='banned',
            field=models.BooleanField(default=False, verbose_name='Banned'),
        ),
    ]
