# Generated by Django 3.0.5 on 2020-04-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0292_auto_20200420_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmanager',
            name='deleted_at',
        ),
    ]
