# Generated by Django 3.0.5 on 2020-04-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0293_businessmanager_sharing_eligibility_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmanager',
            name='sharing_eligibility_status',
        ),
        migrations.AddField(
            model_name='businessmanager',
            name='can_create_ad_account',
            field=models.BooleanField(default=False, verbose_name='Banned'),
        ),
    ]
