# Generated by Django 3.0.5 on 2020-04-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0293_remove_businessmanager_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmanager',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deleted at'),
        ),
    ]
