# Generated by Django 3.0.5 on 2020-04-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0295_merge_20200421_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmanager',
            name='can_create_ad_account',
            field=models.BooleanField(default=False, verbose_name='Can create ad account'),
        ),
        migrations.AlterField(
            model_name='useraccountdaystat',
            name='clicks',
            field=models.IntegerField(default=0, verbose_name='Clicks'),
        ),
        migrations.AlterField(
            model_name='useraccountdaystat',
            name='leads',
            field=models.IntegerField(default=0, verbose_name='Leads'),
        ),
        migrations.AlterField(
            model_name='useraccountdaystat',
            name='visits',
            field=models.IntegerField(default=0, verbose_name='Visits'),
        ),
        migrations.AlterField(
            model_name='usercampaigndaystat',
            name='clicks',
            field=models.IntegerField(default=0, verbose_name='Clicks'),
        ),
        migrations.AlterField(
            model_name='usercampaigndaystat',
            name='leads',
            field=models.IntegerField(default=0, verbose_name='Leads'),
        ),
        migrations.AlterField(
            model_name='usercampaigndaystat',
            name='visits',
            field=models.IntegerField(default=0, verbose_name='Visits'),
        ),
    ]
