# Generated by Django 3.0.5 on 2020-04-25 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0296_auto_20200423_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaccounts', to='core.Account'),
        ),
        migrations.AlterField(
            model_name='adaccountdaystat',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account'),
        ),
        migrations.AlterField(
            model_name='adaccountdaystat',
            name='adaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AdAccount'),
        ),
        migrations.AlterField(
            model_name='fieldssetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraccountdaystat',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Account'),
        ),
        migrations.AlterField(
            model_name='useraccountdaystat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useradaccountdaystat',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account'),
        ),
        migrations.AlterField(
            model_name='useradaccountdaystat',
            name='adaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AdAccount'),
        ),
        migrations.AlterField(
            model_name='useradaccountdaystat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercampaigndaystat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AdAccountUserStat',
        ),
    ]
