# Generated by Django 3.0.5 on 2020-04-22 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0296_auto_20200422_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
