# Generated by Django 3.0.5 on 2020-04-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0297_rule_created_at'),
        ('core', '0296_auto_20200423_0524'),
    ]

    operations = [
    ]
