# Generated by Django 3.0.5 on 2020-04-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0297_auto_20200425_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='story_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='FB story id'),
        ),
    ]
