# Generated by Django 3.0.5 on 2020-04-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0297_auto_20200425_0639'),
        ('core', '0299_campaigntemplate'),
    ]

    operations = [
    ]
