# Generated by Django 3.0.5 on 2020-04-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0300_merge_20200428_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigntemplate',
            name='ads',
        ),
        migrations.RemoveField(
            model_name='campaigntemplate',
            name='adsets',
        ),
    ]
