# Generated by Django 3.0.5 on 2020-05-01 09:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0303_auto_20200428_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaigntemplate',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='adaccount',
            name='pixels',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
