# Generated by Django 3.0.5 on 2020-05-04 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0304_auto_20200501_0915'),
        ('core', '0298_auto_20200429_1454'),
    ]

    operations = [
    ]
