# Generated by Django 3.0.5 on 2020-05-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0305_merge_20200504_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='entity_type',
            field=models.CharField(choices=[('AD', 'Ads'), ('ADSET', 'AdSets'), ('CAMPAIGN', 'Campaigns')], default='AD', max_length=10),
        ),
    ]
