# Generated by Django 3.0.5 on 2020-05-04 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0306_rule_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
