# Generated by Django 3.0.5 on 2020-05-11 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0310_auto_20200511_0717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdsCreateLog',
        ),
    ]
