# Generated by Django 3.0.5 on 2020-05-11 08:08

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0311_delete_adscreatelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsCreateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Waiting'), (10, 'Processing'), (20, 'Error'), (50, 'Success')], default=0)),
                ('status_comment', models.CharField(max_length=1024)),
                ('adaccount_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('campaign_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('adaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AdAccount')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CampaignTemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
