# Generated by Django 3.0.5 on 2020-05-12 08:12

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0313_auto_20200512_0609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adscreatetask',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='adscreatetask',
            name='account',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.Account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adscreatetask',
            name='adaccount_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='adscreatetask',
            name='campaign_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
