# Generated by Django 3.0.6 on 2020-05-14 06:51

import creditcards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0314_auto_20200512_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', creditcards.models.CardNumberField(db_index=True, max_length=25, unique=True, verbose_name='Credit card number')),
                ('comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Financial Comment')),
                ('card_type', models.PositiveSmallIntegerField(choices=[(2, 'American Express'), (3, 'Diners Club'), (4, 'Discover Card'), (6, 'Elo'), (7, 'JCB'), (5, 'MasterCard'), (8, 'MIR'), (9, 'UnionPay'), (0, 'Generic')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('credit_card_type', models.IntegerField()),
                ('display_string', models.CharField(max_length=24)),
                ('exp_month', models.PositiveSmallIntegerField()),
                ('exp_year', models.PositiveSmallIntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField()),
                ('adaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AdAccount')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.CreditCard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
