# Generated by Django 3.0.6 on 2020-05-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0315_creditcard_paymentmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcard',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='credential_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
