# Generated by Django 3.0.6 on 2020-05-14 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0316_auto_20200514_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccounttransaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CreditCard'),
        ),
        migrations.AddField(
            model_name='adaccounttransaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='adaccounttransaction',
            name='tx_type',
            field=models.IntegerField(default=3, verbose_name='TX type'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='adaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='core.AdAccount'),
        ),
    ]
