# Generated by Django 3.0.6 on 2020-05-14 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0317_auto_20200514_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='cards',
            field=models.ManyToManyField(to='core.CreditCard'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='credential_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='FB ID'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
