# Generated by Django 3.0.6 on 2020-05-15 10:17

import creditcards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0318_auto_20200514_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='display_string',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=creditcards.models.CardNumberField(blank=True, db_index=True, max_length=25, null=True, unique=True, verbose_name='Credit card number'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_string', models.CharField(max_length=24)),
                ('hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('card_type', models.PositiveSmallIntegerField(choices=[(2, 'American Express'), (3, 'Diners Club'), (4, 'Discover Card'), (6, 'Elo'), (7, 'JCB'), (5, 'MasterCard'), (8, 'MIR'), (9, 'UnionPay'), (0, 'Generic')])),
                ('number', creditcards.models.CardNumberField(blank=True, db_index=True, max_length=25, null=True, unique=True, verbose_name='Credit card number')),
                ('comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Financial Comment')),
                ('credential_id', models.BigIntegerField(blank=True, null=True, verbose_name='FB ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
