# Generated by Django 3.0.6 on 2020-05-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0319_auto_20200515_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaccount',
            name='cards',
        ),
    ]
