# Generated by Django 3.0.6 on 2020-05-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0320_remove_adaccount_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='cards',
            field=models.ManyToManyField(to='core.Card'),
        ),
    ]
