# Generated by Django 3.0.6 on 2020-05-15 10:57

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0321_adaccount_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=creditcards.models.CardNumberField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Credit card number'),
        ),
    ]
