# Generated by Django 3.0.6 on 2020-05-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0322_auto_20200515_1057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('hash', 'number')},
        ),
    ]
