# Generated by Django 3.0.6 on 2020-05-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0323_auto_20200515_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='adaccount',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card',
        ),
        migrations.RemoveField(
            model_name='adaccounttransaction',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='adaccounttransaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Card'),
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
