# Generated by Django 3.0.6 on 2020-05-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0325_auto_20200519_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaccount',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='card',
            name='credential_id',
        ),
    ]
