# Generated by Django 3.0.6 on 2020-05-19 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0326_auto_20200519_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdAccountCreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('credential_id', models.BigIntegerField(blank=True, null=True, verbose_name='FB ID')),
                ('adaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AdAccount')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Card')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adaccount',
            name='cards',
            field=models.ManyToManyField(through='core.AdAccountCreditCard', to='core.Card'),
        ),
    ]
