# Generated by Django 3.0.6 on 2020-05-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0327_auto_20200519_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
