# Generated by Django 3.0.6 on 2020-05-27 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0328_auto_20200520_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccountcreditcard',
            name='fb_spends',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Spends by FB Transactions'),
        ),
        migrations.AddField(
            model_name='adaccountcreditcard',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total TopUps'),
        ),
        migrations.AddField(
            model_name='adaccountcreditcard',
            name='total_spends',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Full spends'),
        ),
        migrations.AddField(
            model_name='card',
            name='fb_spends',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Spends by FB Transactions'),
        ),
        migrations.AddField(
            model_name='card',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total TopUps'),
        ),
        migrations.AddField(
            model_name='card',
            name='total_spends',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Full spends'),
        ),
        migrations.AlterField(
            model_name='adaccountcreditcard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaccounts', to='core.Card'),
        ),
    ]
