# Generated by Django 3.0.6 on 2020-06-01 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0329_auto_20200527_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaccountcreditcard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_adaccounts', to='core.Card'),
        ),
        migrations.AlterField(
            model_name='adaccounttransaction',
            name='adaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AdAccount'),
        ),
        migrations.AlterField(
            model_name='adaccounttransaction',
            name='end_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Billing end time'),
        ),
        migrations.AlterField(
            model_name='adaccounttransaction',
            name='start_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Billing start time'),
        ),
        migrations.AlterField(
            model_name='adaccounttransaction',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
