# Generated by Django 3.0.6 on 2020-06-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0332_auto_20200601_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaccountcreditcard',
            name='total_spends',
        ),
        migrations.AddField(
            model_name='adaccountcreditcard',
            name='spend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Full spend'),
        ),
    ]
