# Generated by Django 3.0.6 on 2020-06-15 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0333_auto_20200609_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Admin'), (10, 'Mediabuyer'), (20, 'Financier'), (30, 'Farmer'), (40, 'Supplier'), (50, 'Setuper'), (60, 'Manager'), (70, 'Teamlead')], default=10, verbose_name='User role'),
        ),
        migrations.CreateModel(
            name='UserAdAccountDayStatNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Spend')),
                ('funds', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Funds')),
                ('visits', models.IntegerField(default=0, verbose_name='Visits')),
                ('leads', models.IntegerField(default=0, verbose_name='Leads')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clicks')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit')),
                ('adaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AdAccount')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
