# Generated by Django 3.0.6 on 2020-06-15 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0334_auto_20200615_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradaccountdaystatnew',
            name='adaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AdAccount'),
        ),
    ]
