# Generated by Django 3.0.7 on 2020-06-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0335_auto_20200615_0841'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE UNIQUE INDEX date_adacc_camp_user_id_unique ON core_useradaccountdaystatnew (date, COALESCE(adaccount_id, -1), COALESCE(campaign_id, -1), COALESCE(user_id, -1))"
        )
    ]