# Generated by Django 3.0.7 on 2020-06-19 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0336_auto_20200616_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='UserAdAccountDayStatNew',
        ),
    ]
