# Generated by Django 3.0.7 on 2020-06-22 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0337_auto_20200619_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adscreatetask',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CampaignTemplate'),
        ),
    ]
