# Generated by Django 3.0.7 on 2020-06-30 09:18

import core.models.core
import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0339_rule_execution_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total paid'),
        ),
        migrations.CreateModel(
            name='ProcessCSVTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to=core.models.core.get_upload_path, validators=[core.validators.FileValidator(allowed_mimetypes=['text/csv'])], verbose_name='File')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Processing'), (2, 'Success'), (3, 'Error')], default=0, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
