# Generated by Django 3.0.7 on 2020-06-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0340_auto_20200630_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='USD Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Account')),
            ],
        ),
    ]
