# Generated by Django 3.0.7 on 2020-06-30 10:08

import core.models.core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0342_auto_20200630_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processcsvtask',
            name='csv_file',
        ),
        migrations.AddField(
            model_name='processcsvtask',
            name='file',
            field=models.FileField(default='file.txt', upload_to=core.models.core.get_upload_path),
            preserve_default=False,
        ),
    ]
