# Generated by Django 3.0.8 on 2020-07-07 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0344_adaccounttransaction_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccountcreditcard',
            name='display_string',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='adaccountcreditcard',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Card'),
        ),
    ]
