# Generated by Django 3.0.8 on 2020-07-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0345_auto_20200707_0827'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together=set(),
        ),
    ]
