# Generated by Django 3.0.8 on 2020-07-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0346_auto_20200707_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='hash',
        ),
    ]
