# Generated by Django 3.0.8 on 2020-07-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0348_auto_20200707_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccounttransaction',
            name='adaccount_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AdAccountCreditCard'),
        ),
    ]
