# Generated by Django 3.0.8 on 2020-07-08 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0349_adaccounttransaction_adaccount_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaccounttransaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Card'),
        ),
    ]
