# Generated by Django 3.0.8 on 2020-07-13 10:15

from django.db import migrations

def fill_display_name(apps, *args, **kwargs):
    AdAccountCreditCard = apps.get_model('core', 'AdAccountCreditCard')
    for card in AdAccountCreditCard.objects.filter(card__isnull=False):
        card.display_string = card.card.display_string
        card.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0350_auto_20200708_0545'),
    ]

    operations = [
        migrations.RunPython(fill_display_name),
    ]
