# Generated by Django 3.0.8 on 2020-07-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0351_auto_20200713_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('account', 'account'), ('adaccount', 'adaccount'), ('request', 'request'), ('ad', 'ad'), ('finance', 'finance'), ('system', 'system'), ('proxy', 'proxy')], default='account', max_length=64, verbose_name='Notification category'),
        ),
    ]
