# Generated by Django 3.0.8 on 2020-07-13 11:51

from django.db import migrations

def clear_cards(apps, *args, **kwargs):
    Card = apps.get_model('core', 'Card')
    Card.objects.filter(number__isnull=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0352_auto_20200713_1139'),
    ]

    operations = [
        migrations.RunPython(clear_cards),
    ]
