# Generated by Django 3.0.8 on 2020-07-13 11:53

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0353_auto_20200713_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=creditcards.models.CardNumberField(db_index=True, max_length=25, verbose_name='Credit card number'),
        ),
    ]
