# Generated by Django 3.0.8 on 2020-07-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0354_auto_20200713_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountdaystat',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Payment'),
        ),
    ]
