# Generated by Django 3.0.8 on 2020-07-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0356_auto_20200720_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='City'),
        ),
    ]
