# Generated by Django 3.0.8 on 2020-08-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0357_auto_20200720_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowdaystat',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Payment'),
        ),
    ]
