# Generated by Django 3.1 on 2020-08-10 12:18

import django.core.serializers.json
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0361_auto_20200803_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='paid_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='mla_profile_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Multiloginapp profile data'),
        ),
        migrations.AlterField(
            model_name='action',
            name='data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Additional action data'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_review_feedback',
            field=models.JSONField(blank=True, max_length=4096, null=True, verbose_name='Review Feedback'),
        ),
        migrations.AlterField(
            model_name='adaccount',
            name='pixels',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adaccounttransaction',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='RAW transaction data'),
        ),
        migrations.AlterField(
            model_name='adscreatetask',
            name='adaccount_data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='adscreatetask',
            name='campaign_data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='campaign',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='rule',
            name='evaluation_spec',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='rule',
            name='execution_spec',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='rule',
            name='schedule_spec',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='request_data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Request data'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Waiting'), (20, 'Declined'), (50, 'Approve'), (10, 'Processing')], default=0, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='userrequestlog',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Waiting'), (20, 'Declined'), (50, 'Approve'), (10, 'Processing')], db_index=True, null=True),
        ),
    ]
