# Generated by Django 3.1 on 2020-08-11 09:01
import datetime

from django.db import migrations
from django.utils import timezone


def fill_paid_till(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Account = apps.get_model("core", "Account")
    db_alias = schema_editor.connection.alias
    Account.objects.using(db_alias).all().update(
        paid_till=(timezone.now() - datetime.timedelta(days=2)).replace(hour=23, minute=59, second=59, microsecond=999999)
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0362_auto_20200810_1218'),
    ]

    operations = [
        migrations.RunPython(fill_paid_till),
    ]
