# Generated by Django 3.1 on 2020-08-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0364_accountpayment_amount_uah'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='visit_id',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
