# Generated by Django 3.1 on 2020-08-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0365_contact_visit_id'),
        ('core', '0365_leadgen'),
    ]

    operations = [
    ]
