# Generated by Django 3.1 on 2020-08-27 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0366_merge_20200826_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadgen',
            options={'ordering': ('-id',)},
        ),
        migrations.CreateModel(
            name='PageLeadgen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadform_id', models.BigIntegerField()),
                ('leadgen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leadgen')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fbpage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
