# Generated by Django 3.1 on 2020-08-27 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0368_auto_20200827_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageleadgen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
