# Generated by Django 3.1 on 2020-08-31 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0369_pageleadgen_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageleadgen',
            name='last_load',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
