# Generated by Django 3.1 on 2020-08-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0370_pageleadgen_last_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
