# Generated by Django 3.1 on 2020-08-31 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0371_contact_raw_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='raw_data',
        ),
        migrations.CreateModel(
            name='LeadgenLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadform_id', models.BigIntegerField()),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='User ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('country', models.CharField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
                ('zip', models.CharField(blank=True, max_length=8, null=True, verbose_name='ZIP')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('offer', models.CharField(blank=True, max_length=32, null=True)),
                ('network', models.CharField(blank=True, max_length=32, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('referer', models.CharField(blank=True, max_length=4096, null=True)),
                ('visit_id', models.CharField(blank=True, max_length=4096, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Unknown'), (0, 'Male'), (1, 'Female')], null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date added')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('leadgen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leadgen')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fbpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
