# Generated by Django 3.1 on 2020-08-31 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0374_leadgenlead_fb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadgenlead',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
