# Generated by Django 3.1 on 2020-08-31 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0375_auto_20200831_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadgenlead',
            old_name='fb_id',
            new_name='lead_id',
        ),
    ]
