# Generated by Django 3.1 on 2020-09-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0376_auto_20200831_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadgenlead',
            name='exported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date exported'),
        ),
    ]
