# Generated by Django 3.1 on 2020-09-02 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0377_leadgenlead_exported_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadgenLeadConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Payout')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date added')),
                ('exported_at', models.DateTimeField(blank=True, null=True, verbose_name='Date exported')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.leadgenlead')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
