# Generated by Django 3.1 on 2020-09-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0378_leadgenleadconversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='symbol',
            field=models.CharField(db_index=True, max_length=16, null=True, unique=True),
        ),
    ]
