# Generated by Django 3.1 on 2020-09-02 10:32
import random
import string

from django.db import migrations, models

def set_default(apps, *args, **kwargs):
    Campaign = apps.get_model('core', 'Campaign')
    for campaign in Campaign.objects.all():
        symbol = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(10))
        campaign.symbol = symbol
        campaign.save(update_fields=['symbol'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0379_campaign_symbol'),
    ]

    operations = [
        migrations.RunPython(set_default),
        migrations.AlterField(
            model_name='campaign',
            name='symbol',
            field=models.CharField(db_index=True, default=2, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
