# Generated by Django 3.1 on 2020-09-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0380_auto_20200902_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadgenleadconversion',
            name='browser',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='leadgenleadconversion',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='leadgenleadconversion',
            name='connection_type',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='leadgenleadconversion',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='leadgenleadconversion',
            name='device_brand',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='leadgenleadconversion',
            name='device_model',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='leadgenleadconversion',
            name='device_type',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='leadgenleadconversion',
            name='ip',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='leadgenleadconversion',
            name='isp',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='leadgenleadconversion',
            name='language',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='leadgenleadconversion',
            name='region',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
