# Generated by Django 3.1 on 2020-09-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0382_auto_20200902_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadgenleadconversion',
            old_name='browser',
            new_name='browser_name',
        ),
        migrations.AddField(
            model_name='leadgenleadconversion',
            name='offer_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
