# Generated by Django 3.1 on 2020-09-03 07:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0383_auto_20200902_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessShareUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512, verbose_name='Share URL')),
                ('email', models.EmailField(max_length=512, verbose_name='Email')),
                ('status', models.CharField(max_length=16, verbose_name='Status')),
                ('role', models.CharField(max_length=16, verbose_name='Role')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('expire_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expiration data')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.businessmanager')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
