# Generated by Django 3.1 on 2020-09-03 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0384_businessshareurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessshareurl',
            name='share_id',
            field=models.BigIntegerField(default=1, unique=True, verbose_name='Share url id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessshareurl',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_urls', to='core.businessmanager'),
        ),
    ]
