# Generated by Django 3.1 on 2020-09-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0386_auto_20200903_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbpage',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
