# Generated by Django 3.1 on 2020-09-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0388_auto_20200903_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmanager',
            name='share_url',
        ),
        migrations.RemoveField(
            model_name='businessmanager',
            name='shared_at',
        ),
    ]
