# Generated by Django 3.1 on 2020-09-08 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0389_auto_20200903_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='paid_till',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
