# Generated by Django 3.1.1 on 2020-09-28 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0392_fbpage_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageleadgen',
            name='last_load',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
