# Generated by Django 3.1.1 on 2020-10-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0393_auto_20200928_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_review_feedback_code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Review Feedback code'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='story_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='FB story id'),
        ),
    ]
