# Generated by Django 3.1.1 on 2020-10-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0396_account_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkgroup',
            name='base_url',
            field=models.URLField(default='https://fb.me'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkgroup',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
