# Generated by Django 3.1.1 on 2020-10-08 08:47

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0400_auto_20201007_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkgroup',
            name='filter_data',
            field=models.JSONField(default={}, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='linkgroup',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Waiting'), (10, 'Processing'), (20, 'Error'), (50, 'Success')], default=0),
        ),
        migrations.AddField(
            model_name='linkgroup',
            name='status_comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
