# Generated by Django 3.1.1 on 2020-10-08 08:48

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0401_auto_20201008_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkgroup',
            name='filter_data',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
