# Generated by Django 3.1.1 on 2020-10-08 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0402_auto_20201008_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkgroup',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Group UUID'),
        ),
    ]
