# Generated by Django 3.1.1 on 2020-10-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0403_linkgroup_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkgroup',
            name='csv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
