# Generated by Django 3.1.1 on 2020-10-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0404_linkgroup_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkgroup',
            name='total_links',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
