# Generated by Django 3.1.1 on 2020-10-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0405_linkgroup_total_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkgroup',
            name='click_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='linkgroup',
            name='total_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
