# Generated by Django 3.1.1 on 2020-10-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0406_auto_20201008_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
