# Generated by Django 3.1.1 on 2020-10-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0407_auto_20201008_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkgroup',
            name='csv',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=''),
        ),
    ]
