# Generated by Django 3.1.1 on 2020-10-09 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0408_auto_20201008_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkgroup',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='link',
            name='key',
        ),
        migrations.RemoveField(
            model_name='linkgroup',
            name='click_rate',
        ),
        migrations.AlterField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
