# Generated by Django 3.1.1 on 2020-10-09 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0409_auto_20201009_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.linkgroup'),
        ),
    ]
