# Generated by Django 3.1.1 on 2020-10-09 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0410_auto_20201009_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkgroup',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
