# Generated by Django 3.1.1 on 2020-10-12 08:44

import core.models.core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0411_auto_20201009_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='paid_till',
            field=models.DateTimeField(default=core.models.core.default_paid_till),
        ),
    ]
