# Generated by Django 3.1.1 on 2020-10-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0412_auto_20201012_0844'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adaccounttransaction',
            unique_together={('adaccount', 'transaction_id')},
        ),
    ]
