# Generated by Django 3.1.1 on 2020-10-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0414_auto_20201012_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='bills_load_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
