# Generated by Django 3.1.2 on 2020-10-13 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0415_adaccount_bills_load_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccounttransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
