# Generated by Django 3.1.2 on 2020-10-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0417_auto_20201014_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaccounttransaction',
            name='end_at_ts',
        ),
        migrations.RemoveField(
            model_name='adaccounttransaction',
            name='start_at_ts',
        ),
    ]
