# Generated by Django 3.1.2 on 2020-10-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0419_auto_20201014_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('fb_id', models.BigIntegerField(verbose_name='FB ID')),
                ('is_public', models.BooleanField(default=False)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'PageCategory',
                'verbose_name_plural': 'PageCategories',
                'ordering': ('sort',),
            },
        ),
    ]
