# Generated by Django 3.1.2 on 2020-10-23 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0421_auto_20201023_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadgenlead',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.account'),
        ),
        migrations.AlterField(
            model_name='leadgenlead',
            name='lead_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadgenlead',
            name='leadform_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadgenlead',
            name='leadgen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.leadgen'),
        ),
        migrations.AlterField(
            model_name='leadgenlead',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fbpage'),
        ),
        migrations.AlterField(
            model_name='leadgenlead',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
