# Generated by Django 3.1.2 on 2020-10-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0422_auto_20201023_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadgenlead',
            name='zip',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='ZIP'),
        ),
    ]
