# Generated by Django 3.1.2 on 2020-10-26 13:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0423_auto_20201023_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadgenlead',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
    ]
