# Generated by Django 3.1.2 on 2020-10-27 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0424_leadgenlead_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppling_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
