# Generated by Django 3.1.2 on 2020-10-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0425_auto_20201027_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortifyDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=128)),
                ('is_public', models.BooleanField(default=False)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Shortify Domain',
                'verbose_name_plural': 'Shortify Domains',
                'ordering': ('sort',),
            },
        ),
    ]
