# Generated by Django 3.1.2 on 2020-10-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0427_auto_20201027_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcsvtask',
            name='type',
            field=models.CharField(choices=[('payments', 'Payments'), ('leads', 'Leads')], default='payments', max_length=16, verbose_name='CSV Type'),
        ),
    ]
