# Generated by Django 3.1.2 on 2020-10-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0428_processcsvtask_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkgroup',
            name='broadcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.linkgroup'),
        ),
    ]
