# Generated by Django 3.1.2 on 2020-10-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0429_linkgroup_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shortifydomain',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
