# Generated by Django 3.1.3 on 2020-12-04 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0430_auto_20201030_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadgenlead',
            options={'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterField(
            model_name='leadgenlead',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='leadgenlead',
            name='offer',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
