# Generated by Django 3.1.3 on 2020-12-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0430_auto_20201030_0808'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='notification',
            index_together={('id', 'recipient')},
        ),
    ]
