# Generated by Django 3.1.3 on 2020-12-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0431_auto_20201204_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadgenlead',
            name='exported_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date exported'),
        ),
    ]
