# Generated by Django 3.1.3 on 2020-12-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0432_auto_20201204_1048'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='leadgenlead',
            index_together={('created_at', 'id')},
        ),
    ]
