# Generated by Django 3.1.3 on 2020-12-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0433_auto_20201204_1100'),
        ('core', '0431_auto_20201203_1150'),
    ]

    operations = [
    ]
