# Generated by Django 3.1.3 on 2020-12-08 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0434_merge_20201207_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
