# Generated by Django 3.1.3 on 2020-12-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0435_auto_20201208_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadgenlead',
            name='exported_at',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Date exported'),
        ),
    ]
