# Generated by Django 3.1.3 on 2020-12-11 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0436_auto_20201210_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadgenleadconversion',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leadgenlead'),
        ),
        migrations.AlterField(
            model_name='link',
            name='leadgen_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leadgenlead'),
        ),
    ]
