# Generated by Django 3.1.3 on 2020-12-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0437_auto_20201211_0850'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='action',
            index_together={('action_object_content_type', 'action_object_object_id', 'target_object_content_type', 'target_object_id'), ('action_object_content_type', 'action_object_object_id'), ('target_object_content_type', 'target_object_id')},
        ),
    ]
