# Generated by Django 3.1.3 on 2020-12-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0438_auto_20201217_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={},
        ),
    ]
