# Generated by Django 3.1.3 on 2020-12-17 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0439_auto_20201217_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessManagerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('log_type', models.PositiveSmallIntegerField(choices=[(0, 'Status'), (1, 'Account')], db_index=True, default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.businessmanager')),
            ],
            options={
                'index_together': {('start_at', 'end_at')},
            },
        ),
    ]
