# Generated by Django 3.1.4 on 2020-12-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0440_businessmanagerlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadgenlead',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
