# Generated by Django 3.1.4 on 2020-12-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0441_auto_20201225_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadgenlead',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Phone'),
        ),
    ]
