# Generated by Django 3.1.4 on 2021-01-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0442_auto_20201225_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Admin'), (10, 'Mediabuyer'), (20, 'Financier'), (30, 'Farmer'), (40, 'Supplier'), (80, 'Supplier Teamlead'), (50, 'Setuper'), (60, 'Manager'), (70, 'Teamlead')], default=10, verbose_name='User role'),
        ),
    ]
