# Generated by Django 3.1.5 on 2021-01-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0443_auto_20210105_0840'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='useraccountdaystat',
            index_together={('account', 'campaign', 'date')},
        ),
    ]
