# Generated by Django 3.1.5 on 2021-01-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0444_auto_20210107_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='comment',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True, verbose_name='Financial Comment'),
        ),
        migrations.AlterField(
            model_name='card',
            name='display_string',
            field=models.CharField(db_index=True, max_length=24),
        ),
    ]
