# Generated by Django 3.1.5 on 2021-01-18 11:13

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0445_finaccount_fincard_fincardtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaccount',
            name='sensitive_data',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
    ]
