# Generated by Django 3.1.5 on 2021-01-18 11:20

import django.core.serializers.json
from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0446_finaccount_sensitive_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finaccount',
            name='sensitive_data',
        ),
        migrations.AddField(
            model_name='finaccount',
            name='params',
            field=django_cryptography.fields.encrypt(models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
        ),
    ]
