# Generated by Django 3.1.5 on 2021-01-18 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0447_auto_20210118_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaccount',
            name='fin_type',
            field=models.CharField(default='cross', max_length=12),
        ),
        migrations.AddField(
            model_name='fincard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fincard',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_fincards', to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fincard',
            name='display_string',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='fincard',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Card id'),
        ),
    ]
