# Generated by Django 3.1.5 on 2021-01-19 08:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0448_auto_20210118_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='finaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='finaccount',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_finaccs', to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finaccount',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='fincard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='fincard',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='fincardtransaction',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.finaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fincardtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='fincardtransaction',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.fincard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fincardtransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
