# Generated by Django 3.1.5 on 2021-01-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0446_auto_20210127_0930'),
        ('core', '0449_auto_20210119_0841'),
    ]

    operations = [
    ]
