# Generated by Django 3.1.5 on 2021-01-27 12:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0450_merge_20210127_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finaccount',
            old_name='params',
            new_name='data',
        ),
        migrations.AddField(
            model_name='finaccount',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='finaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AddField(
            model_name='fincardtransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='finaccount',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='FinAccountTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.finaccount')),
            ],
        ),
    ]
