# Generated by Django 3.1.6 on 2021-02-23 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0453_auto_20210215_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adaccountlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adaccount_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adaccountlog',
            name='log_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Status'), (1, 'Manager')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='adaccountlog',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='adaccountlog',
            index_together={('start_at', 'end_at'), ('adaccount', 'status', 'log_type', 'end_at')},
        ),
    ]
