# Generated by Django 3.1.6 on 2021-02-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0454_auto_20210223_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adaccount',
            old_name='user',
            new_name='manager',
        ),
    ]
