# Generated by Django 3.1.6 on 2021-02-23 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0456_auto_20210223_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaccount',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
