# Generated by Django 3.1.6 on 2021-02-24 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0457_auto_20210223_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDayStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Spend')),
                ('funds', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Funds')),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Payment')),
                ('visits', models.IntegerField(default=0, verbose_name='Visits')),
                ('leads', models.IntegerField(default=0, verbose_name='Leads')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clicks')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit')),
                ('adaccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.adaccount')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'index_together': {('adaccount', 'campaign', 'user', 'date')},
            },
        ),
    ]
