# Generated by Django 3.1.6 on 2021-02-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0458_userdaystat'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE UNIQUE INDEX date_adacc_camp_user_id ON core_userdaystat (date, COALESCE(adaccount_id, -1), COALESCE(campaign_id, -1), COALESCE(user_id, -1))"
        )
    ]
