# Generated by Django 3.1.6 on 2021-02-24 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0459_auto_20210224_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmanager',
            name='banned',
        ),
        migrations.AddField(
            model_name='businessmanagerlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bm_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessmanagerlog',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessmanagerlog',
            name='log_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manager'), (2, 'Account')], db_index=True, default=2),
        ),
    ]
