# Generated by Django 3.1.6 on 2021-02-24 10:18

from django.db import migrations

def change_log_type(apps, *args, **kwargs):
    BusinessManagerLog = apps.get_model('core', 'BusinessManagerLog')
    BusinessManagerLog.objects.filter(log_type=1).update(log_type=2)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0460_auto_20210224_1018'),
    ]

    operations = [
        migrations.RunPython(change_log_type),
    ]
