# Generated by Django 3.1.6 on 2021-02-25 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0461_auto_20210224_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmanager',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
