# Generated by Django 3.1.7 on 2021-02-25 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0462_businessmanager_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmanagerlog',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.account'),
        ),
    ]
