# Generated by Django 3.1.7 on 2021-02-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0463_auto_20210225_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdaystat',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.account'),
        ),
    ]
