# Generated by Django 3.1.7 on 2021-02-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0464_userdaystat_account'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP INDEX IF EXISTS date_adacc_camp_user_id; "
            "CREATE UNIQUE INDEX date_acc_adacc_camp_user_id ON core_userdaystat (date, COALESCE(account_id, -1), COALESCE(adaccount_id, -1), COALESCE(campaign_id, -1), COALESCE(user_id, -1))"
        )
    ]