# Generated by Django 3.1.7 on 2021-03-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0465_auto_20210226_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='has_leads',
            field=models.BooleanField(default=False),
        ),
    ]
