# Generated by Django 3.1.7 on 2021-03-15 10:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0467_auto_20210311_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
    ]
