# Generated by Django 3.1.7 on 2021-03-15 15:12

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0468_contact_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='device_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
