# Generated by Django 3.1.7 on 2021-03-15 15:13

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0469_contact_device_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='geo_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
