# Generated by Django 3.1.7 on 2021-03-15 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0470_contact_geo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
