# Generated by Django 3.1.7 on 2021-03-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0471_fbpage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='visit_id',
            field=models.UUIDField(db_index=True, editable=False, verbose_name='Visit ID'),
        ),
    ]
