# Generated by Django 3.1.7 on 2021-03-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0472_auto_20210316_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='uuid',
        ),
    ]
