# Generated by Django 3.1.7 on 2021-03-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0473_remove_contact_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='visit_id',
            field=models.UUIDField(db_index=True, verbose_name='Visit ID'),
        ),
    ]
