# Generated by Django 3.1.7 on 2021-03-16 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0474_auto_20210316_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='visit_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='Visit ID'),
        ),
    ]
