# Generated by Django 3.1.7 on 2021-03-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0476_auto_20210316_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='zip',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='ZIP'),
        ),
    ]
