# Generated by Django 3.1.7 on 2021-03-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0477_auto_20210322_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='zip',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ZIP'),
        ),
    ]
