# Generated by Django 3.1.7 on 2021-04-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0478_auto_20210322_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
