# Generated by Django 3.1.7 on 2021-04-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0479_domain_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mla_group_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
