# Generated by Django 3.1.8 on 2021-05-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0481_linkgroup_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadgenlead',
            name='ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
