from datetime import datetime

from django.db.models import Aggregate, Case, F, FloatField, Func, When
from django.db.models.functions import Cast, Round

from dateutil.rrule import MONTHLY, rrule

from core.models.core import User


class CustomRound(Round):
    arity = 2


class Ceil(Func):
    function = 'CEIL'
    template = "%(function)s(%(expressions)s)"


class Epoch(Func):
    function = 'EXTRACT'
    template = "%(function)s('epoch' from %(expressions)s)"


# STATS CONST
EPC = Case(
    When(clicks=0, then=0),
    default=Cast(F('revenue'), FloatField()) / Cast(F('clicks'), FloatField()),
    output_field=FloatField(),
)
CR = Case(
    When(clicks=0, then=0),
    default=(Cast(F('leads'), FloatField()) / Cast(F('clicks'), FloatField())) * 100,
    output_field=FloatField(),
)
CV = Case(
    When(visits=0, then=0),
    default=(Cast(F('leads'), FloatField()) / Cast(F('visits'), FloatField())) * 100,
    output_field=FloatField(),
)
CTR = Case(
    When(visits=0, then=0),
    default=(Cast(F('clicks'), FloatField()) / Cast(F('visits'), FloatField())) * 100,
    output_field=FloatField(),
)
# ROI = Case(When(spend=0, then=0), default=((F('revenue') - F('spend') - F('payment')) / (F('spend') + F('payment'))) * 100)
ROI = Case(When(spend=0, then=0), default=((F('revenue') - F('spend')) / F('spend')) * 100)

SPEND = Case(When(spend=0, then=F('cost')), default=F('spend'))
PROFIT = F('revenue') - F('spend')  # - F('payment')
PROFIT_V2 = F('revenue') - Case(When(spend=0, then=F('cost')), default=F('spend'))


class Median(Aggregate):
    function = 'PERCENTILE_CONT'
    name = 'median'
    output_field = FloatField()
    template = '%(function)s(0.5) WITHIN GROUP (ORDER BY %(expressions)s)'


#  SERIALIZER FIELDS
ACCOUNT_FIELDS_BY_ROLE = {
    User.ADMIN: {
        'list': [
            'id',
            'account',
            'status',
            'auth',
            'manager',
            'created',
            'supplier',
            'payments',
            'spends',
            'funds',
            'comment',
        ],
        'retrieve': [
            'id',
            'tags',
            'country_code',
            'comment',
            'age',
            'has_campaign',
            'status',
            'status_comment',
            'status_duration',
            'last_status',
            'available_statuses',
            'login',
            'password',
            'created_at',
            'created_by',
            'supplier',
            'manager',
            'price',
            'total_paid',
            'fb_access_token',
            'campaign',
            'proxy_host',
            'proxy_port',
            'proxy_login',
            'proxy_password',
            'total_funds',
            'total_spends',
            'fb_spends',
            'fb_spends_today',
            'fb_spends_yesterday',
            'mla_profile_id',
            'phone',
            'email',
            'email_password',
            'date_of_birth',
        ],
        'edit': [
            'tags',
            'login',
            'password',
            'comment',
            'card_balance',
            'supplier',
            'manager',
            'price',
            'fb_access_token',
            'campaign',
            'total_spends',
            'proxy_host',
            'proxy_port',
            'proxy_login',
            'proxy_password',
            'mla_profile_id',
            'phone',
            'email',
            'email_password',
            'date_of_birth',
        ],
    },
    User.MEDIABUYER: {
        'list': ['id', 'account', 'status', 'auth', 'spends', 'funds', 'comment'],
        'retrieve': [
            'id',
            'tags',
            'comment',
            'age',
            'has_campaign',
            'status',
            'country_code',
            'status_comment',
            'status_duration',
            'last_status',
            'available_statuses',
            'login',
            'password',
            'created_at',
            'fb_access_token',
            'campaign',
            'proxy_host',
            'proxy_port',
            'proxy_login',
            'proxy_password',
            'total_funds',
            'fb_spends',
            'fb_spends_today',
            'fb_spends_yesterday',
            'total_paid',
            'phone',
            'email',
            'email_password',
            'date_of_birth',
        ],
        'edit': [
            'tags',
            'comment',
            'status',
            'status_comment',
            'status_duration',
            'password',
            'fb_access_token',
            'campaign',
            'proxy_host',
            'proxy_port',
            'proxy_login',
            'proxy_password',
            'phone',
            'email',
            'email_password',
            'date_of_birth',
        ],
    },
    User.JUNIOR: {
        'list': ['id', 'account', 'status', 'auth', 'spends', 'funds', 'comment'],
        'retrieve': [
            'id',
            'tags',
            'comment',
            'age',
            'has_campaign',
            'status',
            'country_code',
            'status_comment',
            'status_duration',
            'last_status',
            'available_statuses',
            'login',
            'password',
            'created_at',
            'fb_access_token',
            'campaign',
            'proxy_host',
            'proxy_port',
            'proxy_login',
            'proxy_password',
            'total_funds',
            'fb_spends',
            'fb_spends_today',
            'fb_spends_yesterday',
            'total_paid',
            'phone',
            'email',
            'email_password',
            'date_of_birth',
        ],
        'edit': [
            'tags',
            'comment',
            'status',
            'status_comment',
            'status_duration',
            'password',
            'fb_access_token',
            'campaign',
            'proxy_host',
            'proxy_port',
            'proxy_login',
            'proxy_password',
            'phone',
            'email',
            'email_password',
            'date_of_birth',
        ],
    },
    User.TEAMLEAD: {
        'list': ['id', 'account', 'status', 'auth', 'spends', 'funds', 'comment', 'manager'],
        'retrieve': [
            'id',
            'tags',
            'comment',
            'age',
            'manager',
            'has_campaign',
            'status',
            'country_code',
            'status_comment',
            'status_duration',
            'last_status',
            'available_statuses',
            'login',
            'password',
            'created_at',
            'fb_access_token',
            'campaign',
            'proxy_host',
            'proxy_port',
            'proxy_login',
            'proxy_password',
            'total_funds',
            'total_paid',
            'fb_spends',
            'fb_spends_today',
            'fb_spends_yesterday',
            'phone',
            'email',
            'email_password',
            'date_of_birth',
        ],
        'edit': [
            'tags',
            'comment',
            'status',
            'status_comment',
            'status_duration',
            'password',
            'fb_access_token',
            'campaign',
            'proxy_host',
            'proxy_port',
            'proxy_login',
            'proxy_password',
            'phone',
            'email',
            'email_password',
            'date_of_birth',
        ],
    },
    User.FINANCIER: {
        'list': ['id', 'account', 'status', 'auth', 'spends', 'funds', 'manager', 'payments', 'comment', 'supplier'],
        'retrieve': [
            'id',
            'tags',
            'comment',
            'age',
            'has_campaign',
            'country_code',
            'status',
            'status_comment',
            'status_duration',
            'last_status',
            'available_statuses',
            'login',
            'password',
            'created_at',
            'created_by',
            'manager',
            'supplier',
            'price',
            'fb_access_token',
            'campaign',
            'fb_spends',
            'fb_spends_today',
            'fb_spends_yesterday',
            'total_funds',
            'total_spends',
            'total_paid',
        ],
        'edit': [
            'tags',
            'password',
            'comment',
            'card_balance',
            'price',
            'total_spends',
            'fb_access_token',
            'campaign',
        ],
    },
    User.FARMER: {
        'list': ['id', 'account', 'status', 'auth', 'spends', 'funds', 'comment'],
        'retrieve': [
            'id',
            'tags',
            'comment',
            'age',
            'has_campaign',
            'fb_access_token',
            'country_code',
            'campaign',
            'status',
            'status_comment',
            'status_duration',
            'last_status',
            'available_statuses',
            'login',
            'password',
            'created_at',
            'proxy_host',
            'proxy_port',
            'proxy_login',
            'proxy_password',
            'phone',
            'email',
            'email_password',
            'date_of_birth',
        ],
        'edit': [
            'tags',
            'comment',
            'password',
            'status',
            'status_comment',
            'fb_access_token',
            'campaign',
            'proxy_host',
            'proxy_port',
            'proxy_login',
            'proxy_password',
            'phone',
            'email',
            'email_password',
            'date_of_birth',
        ],
    },
    User.SUPPLIER: {
        'list': ['id', 'account', 'status', 'auth', 'payments', 'comment'],
        'retrieve': [
            'id',
            'tags',
            'comment',
            'age',
            'has_campaign',
            'country_code',
            'status',
            'status_comment',
            'status_duration',
            'last_status',
            'available_statuses',
            'login',
            'password',
            'created_at',
            'price',
            'phone',
            'email',
            'email_password',
            'date_of_birth',
        ],
        'edit': [
            'tags',
            'comment',
            'status',
            'status_comment',
            'login',
            'password',
            'price',
            'phone',
            'email',
            'email_password',
            'date_of_birth',
        ],
    },
    User.SETUPER: {
        'list': ['id', 'account', 'status', 'auth', 'manager', 'comment'],
        'retrieve': [
            'id',
            'tags',
            'comment',
            'age',
            'has_campaign',
            'country_code',
            'manager',
            'status',
            'status_comment',
            'status_duration',
            'last_status',
            'available_statuses',
            'login',
            'password',
            'fb_access_token',
            'campaign',
            'proxy_host',
            'proxy_port',
            'proxy_login',
            'proxy_password',
        ],
        'edit': [
            'tags',
            'comment',
            'status',
            'status_comment',
            'password',
            'fb_access_token',
            'campaign',
            'proxy_host',
            'proxy_port',
            'proxy_login',
            'proxy_password',
        ],
    },
    User.MANAGER: {
        'list': ['id', 'account', 'status', 'auth', 'manager', 'comment', 'spends', 'funds', 'created', 'supplier'],
        'retrieve': [
            'id',
            'tags',
            'comment',
            'age',
            'has_campaign',
            'country_code',
            'manager',
            'created_at',
            'created_by',
            'price',
            'supplier',
            'status',
            'status_comment',
            'status_duration',
            'last_status',
            'available_statuses',
            'login',
            'password',
            'fb_access_token',
            'campaign',
            'proxy_host',
            'proxy_port',
            'proxy_login',
            'proxy_password',
            'mla_profile_id',
            'phone',
            'email',
            'email_password',
            'date_of_birth',
            'total_paid',
        ],
        'edit': [
            'tags',
            'comment',
            'supplier',
            'manager',
            'status',
            'status_comment',
            'login',
            'password',
            'fb_access_token',
            'proxy_host',
            'proxy_port',
            'proxy_login',
            'proxy_password',
            'mla_profile_id',
            'price',
            'phone',
            'email',
            'email_password',
            'date_of_birth',
        ],
    },
}

ACCOUNT_FIELDS_BY_ROLE[User.SUPPLIER_TEAMLEAD] = ACCOUNT_FIELDS_BY_ROLE[User.SUPPLIER]
ACCOUNT_FIELDS_BY_ROLE[User.SUPPLIER_TEAMLEAD]['list'].append('supplier')
ACCOUNT_FIELDS_BY_ROLE[User.SUPPLIER_TEAMLEAD]['edit'].append('supplier')
ACCOUNT_FIELDS_BY_ROLE[User.SUPPLIER_TEAMLEAD]['retrieve'].append('supplier')

# Dashboard blocks
# Только list
DASHBOARD_FIELDS_BY_ROLE = {
    User.ADMIN: {'list': ['kpi', 'spends', 'statuses', 'day_stats', 'stats', 'geo', 'user_stats', 'banned']},
    User.MEDIABUYER: {'list': ['kpi', 'statuses', 'day_stats', 'stats', 'geo', 'user_stats']},
    User.JUNIOR: {'list': ['kpi', 'statuses', 'day_stats', 'stats']},
    User.TEAMLEAD: {'list': ['kpi', 'statuses', 'day_stats', 'stats', 'geo', 'user_stats']},
    User.FINANCIER: {'list': ['kpi', 'statuses', 'day_stats', 'stats', 'geo', 'user_stats']},
    User.FARMER: {'list': []},
    User.SUPPLIER: {'list': ['statuses']},
    User.SUPPLIER_TEAMLEAD: {'list': ['statuses']},
    User.SETUPER: {'list': []},
    User.MANAGER: {'list': ['statuses']},
}


def months_list(start_month, start_year, end_month, end_year):
    start = datetime(start_year, start_month, 1)
    end = datetime(end_year, end_month, 1)
    return [(d.month, d.year) for d in rrule(MONTHLY, dtstart=start, until=end)]
